'use client';

import {siteConfirm,sitePrompt} from './SiteDialog';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';

type Product={id:string;name:string;borrow_asset:string;collateral_asset:string;term_mode:string;term_days:number|null;hourly_rate:number|null;annual_rate:number|null;initial_ltv:number;margin_call_ltv:number;liquidation_ltv:number;min_borrow:number;max_borrow:number|null;provider_code:string|null;provider_product_code:string|null;status:string;visible:boolean;sort_order:number};
type Loan={id:string;loan_no:string;user_id:string;collateral_quantity:number;collateral_asset:string;principal:number;borrow_asset:string;current_ltv:number|null;status:string;provider_loan_id?:string|null;provider_status?:string|null;accrued_interest?:number;repaid_principal?:number;repaid_interest?:number};
type Snapshot={counts?:Record<string,number>;principal_active?:number;interest_accrued?:number;products?:Product[];recent_loans?:Loan[]};
const empty={id:'',name:'',borrow_asset:'USDT',collateral_asset:'BTC',term_mode:'FLEXIBLE',term_days:'',hourly_rate:'',annual_rate:'',initial_ltv:'0.65',margin_call_ltv:'0.75',liquidation_ltv:'0.85',min_borrow:'100',max_borrow:'',provider_code:'',provider_product_code:'',status:'DRAFT',visible:false,sort_order:'100'};

export default function AdminCryptoLoanClient(){
 const supabase=useMemo(()=>createBrowserSupabase(),[]);const [admin,setAdmin]=useState<boolean|null>(null);const [snap,setSnap]=useState<Snapshot>({});const [v2,setV2]=useState<any>({products:[],loans:[]});const [form,setForm]=useState<any>(empty);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const [actionLoan,setActionLoan]=useState<string>('');const [loanFilter,setLoanFilter]=useState('ALL');const [detailLoan,setDetailLoan]=useState<any|null>(null);
 async function load(){setMsg('');const {data:{user}}=await supabase.auth.getUser();const ok=user?.app_metadata?.role==='admin'||user?.app_metadata?.role==='superadmin'||user?.app_metadata?.superadmin===true;setAdmin(ok);if(!ok)return;const [{data,error},{data:v2data,error:v2err}]=await Promise.all([supabase.rpc('admin_crypto_loan_snapshot'),supabase.rpc('admin_crypto_loan_snapshot_v2')]);if(error)setMsg(error.message);else if(v2err)setMsg(v2err.message);setSnap((data||{}) as Snapshot);setV2(v2data||{products:[],loans:[]})}
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const requested=params.get('status');if(requested)setLoanFilter(requested);load();const id=setInterval(load,5000);return()=>clearInterval(id)},[]);
 function edit(p:Product){setForm({...p,term_days:p.term_days??'',hourly_rate:p.hourly_rate??'',annual_rate:p.annual_rate??'',max_borrow:p.max_borrow??'',provider_code:p.provider_code??'',provider_product_code:p.provider_product_code??'',sort_order:String(p.sort_order)})}
 async function save(){setBusy(true);setMsg('');const {error}=await supabase.rpc('admin_upsert_crypto_loan_product',{p_id:form.id||null,p_name:form.name,p_borrow_asset:form.borrow_asset,p_collateral_asset:form.collateral_asset,p_term_mode:form.term_mode,p_term_days:form.term_mode==='FIXED'?Number(form.term_days):null,p_hourly_rate:Number(form.hourly_rate),p_annual_rate:form.annual_rate===''?null:Number(form.annual_rate),p_initial_ltv:Number(form.initial_ltv),p_margin_call_ltv:Number(form.margin_call_ltv),p_liquidation_ltv:Number(form.liquidation_ltv),p_min_borrow:Number(form.min_borrow||0),p_max_borrow:form.max_borrow===''?null:Number(form.max_borrow),p_provider_code:form.provider_code||null,p_provider_product_code:form.provider_product_code||null,p_status:form.status,p_visible:!!form.visible,p_sort_order:Number(form.sort_order||100)});setBusy(false);if(error){setMsg(error.message);return;}setMsg('대출 상품이 저장되었습니다.');setForm(empty);await load()}
 async function runAction(loan:Loan,action:string){
  let reference:string|null=null,note:string|null=null,amount:number|null=null,surplus:number|null=null;
  if(action==='DISBURSE'||action==='RELEASE_COLLATERAL'){reference=(await sitePrompt(action==='DISBURSE'?'지급/담보처리 참조번호를 입력하세요.':'담보 반환 참조번호를 입력하세요.','',{title:'참조번호 입력'}))||null;if(!reference)return;}
  if(action==='REJECT'||action==='CANCEL'){note=(await sitePrompt(action==='REJECT'?'거절 사유를 입력하세요.':'취소 사유를 입력하세요.','',{title:'처리 사유'}))||null;if(!note)return;}
  if(action==='COMPLETE_LIQUIDATION'){const a=await sitePrompt('청산 처리금액을 입력하세요.','0',{title:'청산 처리',inputType:'number'});if(a===null)return;const s=await sitePrompt('회원에게 반환할 잔여금이 있으면 입력하세요.','0',{title:'청산 처리',inputType:'number'});if(s===null)return;amount=Number(a);surplus=Number(s);reference=(await sitePrompt('청산 참조번호를 입력하세요.','',{title:'청산 처리'}))||null;if(!reference)return;}
  const labels:Record<string,string>={APPROVE:'승인',DISBURSE:'지급 완료',REJECT:'거절',CANCEL:'취소',CONFIRM_REPAYMENT:'상환 확정',RELEASE_COLLATERAL:'담보 반환',COMPLETE_LIQUIDATION:'청산 완료'};
  if(!(await siteConfirm(`${loan.loan_no} 건을 '${labels[action]||action}' 처리하시겠습니까?`,{title:'대출 처리 확인'})))return;
  setActionLoan(loan.id);setMsg('');
  const {error}=await supabase.rpc('admin_manual_crypto_loan_action',{p_loan:loan.id,p_action:action,p_reference:reference,p_note:note,p_amount:amount,p_surplus:surplus});
  setActionLoan('');if(error){setMsg(error.message);return;}setMsg(`${loan.loan_no} · ${labels[action]||action} 처리 완료`);await load();
 }
 async function v2Approve(l:any){
  const payout=Number(l.principal||0).toLocaleString();const reserve=Number(l.reserve_value_usdt||l.initial_value||0).toLocaleString();
  if(!(await siteConfirm(`대출을 승인하면 회원 자산에 ${payout} USDT가 지급됩니다.\n\n동시에 ${reserve} USDT 상당의 자산가치가 대출 담보로 설정되어 출금이 제한됩니다.\n\n현재 총 자산: ${Number(l.account_total_value||0).toLocaleString()} USDT\n기존 포함 총 담보제한: ${Number(l.account_total_reserve||0).toLocaleString()} USDT\n승인 가능: ${l.approval_available===false?'아니오':'예'}\n\n계속하시겠습니까?`,{title:'대출 승인'})))return;
  setActionLoan(l.id);const {error}=await supabase.rpc('admin_approve_crypto_loan_v2',{p_loan:l.id});setActionLoan('');
  if(error){setMsg(error.message);return}setMsg(`${l.loan_no} 승인 및 지급 완료`);await load();
 }
 async function v2Reject(l:any){
  const reason=await sitePrompt('대출 거절 사유를 입력하세요.','',{title:'대출 거절'});if(!reason)return;
  setActionLoan(l.id);const {error}=await supabase.rpc('admin_reject_crypto_loan_v2',{p_loan:l.id,p_reason:reason});setActionLoan('');
  if(error){setMsg(error.message);return}setMsg(`${l.loan_no} 거절 및 담보 LOCK 해제 완료`);await load();
 }
 async function v2OfferExtension(l:any){
  if(!l.extension_id){setMsg('연장 요청 정보를 찾을 수 없습니다.');return}
  const days=await sitePrompt('추가 연장기간(일)을 입력하세요.','7',{title:'연장 조건 설정',inputType:'number'});if(days===null)return;
  const rate=await sitePrompt('변경 이자율(%)을 입력하세요.','1.5',{title:'연장 조건 설정',inputType:'number'});if(rate===null)return;
  const note=await sitePrompt('관리자 메모를 입력하세요.','',{title:'연장 조건 설정'});
  setActionLoan(l.id);const {error}=await supabase.rpc('admin_offer_crypto_loan_extension',{p_extension:l.extension_id,p_additional_days:Number(days),p_new_interest_rate:Number(rate)/100,p_admin_note:note||null});setActionLoan('');
  if(error){setMsg(error.message);return}setMsg(`${l.loan_no} 연장 조건 제시 완료`);await load();
 }
 async function v2RejectExtension(l:any){
  if(!l.extension_id)return;const note=await sitePrompt('연장 거절 사유를 입력하세요.','',{title:'연장 거절'});if(!note)return;
  setActionLoan(l.id);const {error}=await supabase.rpc('admin_reject_crypto_loan_extension',{p_extension:l.extension_id,p_note:note});setActionLoan('');
  if(error){setMsg(error.message);return}setMsg(`${l.loan_no} 연장 요청 거절 완료`);await load();
 }
 async function v2Overdue(l:any){
  if(!(await siteConfirm(`${l.loan_no} 대출을 연체 확정 처리하고 상품의 연체 이자율을 적용할까요?`,{title:'연체 승인'})))return;
  setActionLoan(l.id);const {error}=await supabase.rpc('admin_mark_crypto_loan_overdue',{p_loan:l.id});setActionLoan('');
  if(error){setMsg(error.message);return}setMsg(`${l.loan_no} 연체 승인 완료`);await load();
 }
 async function v2Seize(l:any){
  const reason=await sitePrompt('담보 회수 사유를 입력하세요.','만기 미상환 협의 후 담보 회수',{title:'담보 회수'});if(!reason)return;
  if(!(await siteConfirm(`${l.loan_no}에 연결된 담보 ${l.collateral_locked_quantity} ${l.asset_symbol}만 회수합니다. 계속할까요?`,{title:'담보 회수 확인'})))return;
  setActionLoan(l.id);const {error}=await supabase.rpc('admin_seize_crypto_loan_collateral',{p_loan:l.id,p_reason:reason});setActionLoan('');
  if(error){setMsg(error.message);return}setMsg(`${l.loan_no} 담보 회수 완료`);await load();
 }
 async function editTerms(p:any){
  const base=await sitePrompt('기본 이자율(%)',''+(Number(p.base_interest_rate||.01)*100),{title:'대출상품 운영조건',inputType:'number'});if(base===null)return;
  const overdue=await sitePrompt('연체 이자율(%)',''+(Number(p.overdue_interest_rate||.028)*100),{title:'대출상품 운영조건',inputType:'number'});if(overdue===null)return;
  const days=await sitePrompt('기본 대출기간(일)',''+Number(p.term_days||7),{title:'대출상품 운영조건',inputType:'number'});if(days===null)return;
  const ltv=await sitePrompt('최대 LTV(%)',''+(Number(p.max_ltv||.8)*100),{title:'대출상품 운영조건',inputType:'number'});if(ltv===null)return;
  setBusy(true);const {error}=await supabase.rpc('admin_update_crypto_loan_product_terms',{p_product:p.id,p_base_interest_rate:Number(base)/100,p_overdue_interest_rate:Number(overdue)/100,p_term_days:Number(days),p_max_ltv:Number(ltv)/100,p_extension_allowed:true});setBusy(false);
  if(error){setMsg(error.message);return}setMsg('대출상품 운영조건이 저장되었습니다.');await load();
 }
 function v2Actions(l:any){
  const common={height:30,padding:'0 9px',border:'1px solid #343a3e',borderRadius:6,background:'#171a1c',color:'#fff',fontSize:11,cursor:'pointer'} as const;
  const primary={...common,background:'#b9ff31',color:'#111',border:0,fontWeight:800} as const;
  const danger={...common,border:'1px solid #71323b',color:'#ff8190'} as const;
  const disabled=actionLoan===l.id;
  if(l.status==='PENDING')return <div style={{display:'flex',gap:5,flexWrap:'wrap'}}><button disabled={disabled} style={primary} onClick={()=>v2Approve(l)}>대출 승인</button><button disabled={disabled} style={danger} onClick={()=>v2Reject(l)}>대출 거절</button></div>;
  if(l.status==='EXTENSION_REQUESTED')return <div style={{display:'flex',gap:5,flexWrap:'wrap'}}><button disabled={disabled} style={primary} onClick={()=>v2OfferExtension(l)}>연장 조건 설정</button><button disabled={disabled} style={danger} onClick={()=>v2RejectExtension(l)}>연장 거절</button></div>;
  if(l.status==='EXTENSION_OFFERED')return <div style={{display:'flex',gap:5,flexWrap:'wrap'}}><span style={{color:'#b9ff31',fontSize:11}}>회원 동의 대기</span><button disabled={disabled} style={danger} onClick={()=>v2RejectExtension(l)}>제안 취소</button></div>;
  if(l.status==='OVERDUE_REVIEW')return <div style={{display:'flex',gap:5,flexWrap:'wrap'}}><button disabled={disabled} style={primary} onClick={()=>v2Overdue(l)}>연체 승인</button><button disabled={disabled} style={danger} onClick={()=>v2Seize(l)}>담보 회수</button></div>;
  if(l.status==='OVERDUE')return <button disabled={disabled} style={danger} onClick={()=>v2Seize(l)}>담보 회수</button>;
  if(l.status==='COLLATERAL_SEIZED')return <span style={{color:'#ff8190'}}>회수 완료</span>;
  if(l.status==='REPAID')return <span style={{color:'#b9ff31'}}>상환 완료</span>;
  return <span style={{color:'#697176'}}>{l.status}</span>;
 }
 function actions(l:Loan){
  const common={height:30,padding:'0 9px',border:'1px solid #343a3e',borderRadius:6,background:'#171a1c',color:'#fff',fontSize:11,cursor:'pointer'} as const;
  const primary={...common,background:'#b9ff31',color:'#111',border:0,fontWeight:800} as const;
  const danger={...common,border:'1px solid #71323b',color:'#ff8190'} as const;
  const disabled=actionLoan===l.id;
  if(['REQUESTED','COLLATERAL_PENDING','PROVIDER_PENDING'].includes(l.status))return <div style={{display:'flex',gap:5,flexWrap:'wrap'}}><button disabled={disabled} style={primary} onClick={()=>runAction(l,'APPROVE')}>승인</button><button disabled={disabled} style={primary} onClick={()=>runAction(l,'DISBURSE')}>지급완료</button><button disabled={disabled} style={danger} onClick={()=>runAction(l,'REJECT')}>거절</button><button disabled={disabled} style={common} onClick={()=>runAction(l,'CANCEL')}>취소</button></div>;
  if(['ACTIVE','MARGIN_CALL','REPAYMENT_PENDING'].includes(l.status))return <div style={{display:'flex',gap:5,flexWrap:'wrap'}}><button disabled={disabled} style={primary} onClick={()=>runAction(l,'CONFIRM_REPAYMENT')}>상환확정</button><button disabled={disabled} style={common} onClick={()=>runAction(l,'CANCEL')}>강제취소</button>{['MARGIN_CALL'].includes(l.status)&&<button disabled={disabled} style={danger} onClick={()=>runAction(l,'COMPLETE_LIQUIDATION')}>청산완료</button>}</div>;
  if(l.status==='REPAID')return <button disabled={disabled} style={primary} onClick={()=>runAction(l,'RELEASE_COLLATERAL')}>담보반환</button>;
  if(['LIQUIDATION_PENDING','LIQUIDATING'].includes(l.status))return <button disabled={disabled} style={danger} onClick={()=>runAction(l,'COMPLETE_LIQUIDATION')}>청산완료</button>;
  return <span style={{color:'#697176'}}>처리 완료</span>;
 }
 if(admin===null)return <main className="wrap"><p>Loading...</p></main>;if(!admin)return <main className="wrap"><div className="warning">관리자 권한이 필요합니다.</div></main>;
 const c=snap.counts||{};return <main style={{minHeight:'calc(100vh - 72px)',background:'#0b0d0e',padding:'42px 0 90px',color:'#fff'}}><div className="xtShell"><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'end',marginBottom:20}}><div><span style={{color:'#b9ff31',fontSize:12,fontWeight:900,letterSpacing:'.14em'}}>CRYPTO LOAN ADMIN</span><h1 style={{fontSize:40,margin:'8px 0 0'}}>Collateral Loan Control</h1><p style={{color:'#7f888d',fontSize:12}}>지급·승인·거절·취소·상환확정·담보반환·청산은 모두 관리자 수동 처리입니다.</p></div></div>{msg&&<div style={{padding:12,border:'1px solid #4b4930',background:'#211f12',borderRadius:9,marginBottom:14,color:'#e4cf74'}}>{msg}</div>}
 <section style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:9,marginBottom:16}}>{[['신청 대기',c.requested||0],['활성',c.active||0],['Margin Call',c.margin_call||0],['청산 대기',c.liquidation_pending||0],['활성 원금',Number(snap.principal_active||0).toLocaleString()],['누적 이자',Number(snap.interest_accrued||0).toLocaleString()]].map(([k,v])=><div key={String(k)} style={{padding:14,border:'1px solid #272c2f',borderRadius:11,background:'#111416'}}><small style={{color:'#788186'}}>{k}</small><b style={{display:'block',fontSize:18,marginTop:6}}>{String(v)}</b></div>)}</section>
 <section style={{display:'grid',gridTemplateColumns:'.85fr 1.15fr',gap:14}}><div style={{padding:18,border:'1px solid #272c2f',borderRadius:14,background:'#111416'}}><h2 style={{fontSize:18,margin:'0 0 14px'}}>{form.id?'상품 수정':'새 상품'}</h2><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:9}}>{[['name','상품명'],['borrow_asset','대출 자산'],['collateral_asset','담보 자산'],['hourly_rate','시간당 금리(소수)'],['annual_rate','연 이자율(소수)'],['initial_ltv','초기 LTV'],['margin_call_ltv','마진콜 LTV'],['liquidation_ltv','청산 LTV'],['min_borrow','최소 대출'],['max_borrow','최대 대출'],['provider_code','Provider 코드'],['provider_product_code','Provider 상품코드'],['sort_order','정렬순서']].map(([key,label])=><label key={key} style={{display:'grid',gap:5,fontSize:11,color:'#828b90'}}>{label}<input value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} style={{height:38,border:'1px solid #30363a',background:'#181c1e',borderRadius:7,color:'#fff',padding:'0 9px'}}/></label>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:9,marginTop:9}}><label style={{display:'grid',gap:5,fontSize:11,color:'#828b90'}}>기간<select value={form.term_mode} onChange={e=>setForm({...form,term_mode:e.target.value})} style={{height:38,background:'#181c1e',color:'#fff',border:'1px solid #30363a',borderRadius:7}}><option value="FLEXIBLE">FLEXIBLE</option><option value="FIXED">FIXED</option></select></label><label style={{display:'grid',gap:5,fontSize:11,color:'#828b90'}}>기간(일)<input disabled={form.term_mode!=='FIXED'} value={form.term_days} onChange={e=>setForm({...form,term_days:e.target.value})} style={{height:38,border:'1px solid #30363a',background:'#181c1e',borderRadius:7,color:'#fff',padding:'0 9px'}}/></label><label style={{display:'grid',gap:5,fontSize:11,color:'#828b90'}}>상태<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} style={{height:38,background:'#181c1e',color:'#fff',border:'1px solid #30363a',borderRadius:7}}>{['DRAFT','ACTIVE','PAUSED','DISABLED'].map(x=><option key={x}>{x}</option>)}</select></label></div><label style={{display:'flex',gap:8,margin:'12px 0',fontSize:12}}><input type="checkbox" checked={!!form.visible} onChange={e=>setForm({...form,visible:e.target.checked})}/>회원 화면 노출</label><div style={{display:'flex',gap:8}}><button disabled={busy} onClick={save} style={{height:40,padding:'0 16px',border:0,borderRadius:7,background:'#b9ff31',fontWeight:900}}>{busy?'저장 중...':'저장'}</button>{form.id&&<button onClick={()=>setForm(empty)} style={{height:40,padding:'0 16px',border:'1px solid #30363a',borderRadius:7,background:'#171a1c',color:'#fff'}}>새 상품</button>}</div></div>
 <div style={{padding:18,border:'1px solid #272c2f',borderRadius:14,background:'#111416'}}><h2 style={{fontSize:18,margin:'0 0 14px'}}>상품 목록</h2><div style={{display:'grid',gap:8}}>{(snap.products||[]).map(p=><button key={p.id} onClick={()=>edit(p)} style={{textAlign:'left',padding:12,border:'1px solid #262b2e',borderRadius:9,background:'#171a1c',color:'#fff',cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><b>{p.name}</b><span style={{color:p.status==='ACTIVE'?'#b9ff31':'#8a9296'}}>{p.status}{p.visible?' · VISIBLE':''}</span></div><small style={{display:'block',marginTop:5,color:'#788186'}}>{p.collateral_asset} → {p.borrow_asset} · {p.term_mode}{p.term_days?` ${p.term_days}D`:''} · Hourly {Number(p.hourly_rate||0)} · LTV {Number(p.initial_ltv)*100}%/{Number(p.margin_call_ltv)*100}%/{Number(p.liquidation_ltv)*100}%</small></button>)}</div></div></section>
 <section style={{marginTop:16,padding:18,border:'1px solid #272c2f',borderRadius:14,background:'#111416'}}>
  <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,marginBottom:14}}><div><h2 style={{fontSize:18,margin:0}}>대출관리 · 코인 담보 7일 대출</h2><small style={{color:'#738087'}}>신청 대기 → 관리자 승인 → 잔액 지급 → ACTIVE · 담보는 내부거래 가능 / 출금 제한</small></div><span style={{color:'#b9ff31',fontSize:11}}>5초 자동 갱신</span></div>
  <div style={{display:'flex',gap:6,flexWrap:'wrap',marginBottom:12}}>{[['ALL','전체'],['PENDING','승인대기'],['ACTIVE','진행중'],['EXTENSION_REQUESTED','연장요청'],['OVERDUE_REVIEW','연체검토'],['OVERDUE','연체'],['REPAID','상환완료'],['REJECTED','거절']].map(([key,label])=>{const count=key==='ALL'?(v2.loans||[]).length:(v2.loans||[]).filter((x:any)=>key==='ACTIVE'?['ACTIVE','EXTENDED','EXTENSION_OFFERED'].includes(x.status):x.status===key).length;return <button key={key} onClick={()=>setLoanFilter(key)} style={{height:34,padding:'0 11px',border:'1px solid '+(loanFilter===key?'#8fcf31':'#30383c'),borderRadius:7,background:loanFilter===key?'#17220f':'#121719',color:loanFilter===key?'#c6ff6b':'#9aa4a8',fontSize:11,cursor:'pointer',fontWeight:700}}>{label}{count>0&&<span style={{marginLeft:6,minWidth:18,height:18,padding:'0 5px',display:'inline-grid',placeItems:'center',borderRadius:999,background:key==='PENDING'||key==='EXTENSION_REQUESTED'||key==='OVERDUE_REVIEW'?'#f0b84c':'#232b2f',color:key==='PENDING'||key==='EXTENSION_REQUESTED'||key==='OVERDUE_REVIEW'?'#171006':'#aab4b8',fontSize:9}}>{count}</span>}</button>})}</div>
  <div style={{display:'grid',gap:8,marginBottom:14}}>{(v2.products||[]).filter((p:any)=>p.name==='코인 담보 7일 대출').map((p:any)=><div key={p.id} style={{display:'grid',gridTemplateColumns:'1fr auto',gap:12,alignItems:'center',padding:12,border:'1px solid #263036',borderRadius:9,background:'#0e1214'}}><div><b>{p.name}</b><small style={{display:'block',marginTop:5,color:'#758086'}}>LTV {Number(p.max_ltv||0)*100}% · {p.term_days}일 · 기본 {Number(p.base_interest_rate||0)*100}% · 연체 {Number(p.overdue_interest_rate||0)*100}% · 담보 {(p.allowed_collateral_assets||[]).join(' / ')}</small></div><button disabled={busy} onClick={()=>editTerms(p)} style={{height:34,padding:'0 11px',border:'1px solid #3a454a',borderRadius:7,background:'#151b1e',color:'#fff',cursor:'pointer'}}>운영조건 수정</button></div>)}</div>
  <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:11,minWidth:2050}}><thead><tr style={{color:'#758085'}}>{['회원','대출 ID','상품명','신청금액','담보자산','담보 평가금액','LTV','신청시간','현재 총자산','총 담보제한','승인 가능','이자율','만기일','상태','연장','연체','상세','관리'].map(x=><th key={x} style={{textAlign:'left',padding:9,whiteSpace:'nowrap'}}>{x}</th>)}</tr></thead><tbody>{(v2.loans||[]).filter((l:any)=>loanFilter==='ALL'||l.status===loanFilter||(loanFilter==='ACTIVE'&&['ACTIVE','EXTENDED','EXTENSION_OFFERED'].includes(l.status))).map((l:any)=><tr key={l.id} style={{borderTop:'1px solid #23282b'}}><td style={{padding:9}}>{l.email||String(l.user_id).slice(0,8)+'…'}</td><td style={{padding:9}}>{l.loan_no}</td><td style={{padding:9}}>{l.product_name||'—'}</td><td style={{padding:9}}>{Number(l.principal||0).toLocaleString()} USDT</td><td style={{padding:9}}>{l.asset_symbol||l.collateral_asset}<small style={{display:'block',color:'#657176'}}>{Number(l.collateral_locked_quantity||l.collateral_quantity||0).toLocaleString(undefined,{maximumFractionDigits:8})}</small></td><td style={{padding:9}}>{Number(l.reserve_value_usdt||l.initial_value||0).toLocaleString()} USDT</td><td style={{padding:9}}>{l.current_ltv==null?'—':(Number(l.current_ltv)*100).toFixed(2)+'%'}</td><td style={{padding:9}}>{new Date(l.created_at).toLocaleString('ko-KR')}</td><td style={{padding:9}}>{Number(l.account_total_value||0).toLocaleString()} USDT</td><td style={{padding:9}}>{Number(l.account_total_reserve||0).toLocaleString()} USDT</td><td style={{padding:9,color:l.approval_available===false?'#ff8190':'#b9ff31'}}>{l.status==='PENDING'?(l.approval_available===false?'불가':'가능'):'—'}</td><td style={{padding:9}}>{l.interest_rate==null?'—':(Number(l.interest_rate)*100).toFixed(2)+'%'}</td><td style={{padding:9}}>{l.due_at?new Date(l.due_at).toLocaleString('ko-KR'):'—'}</td><td style={{padding:9}}><b>{l.status}</b><small style={{display:'block',color:'#69757a',marginTop:3}}>담보 {l.collateral_status||'—'}</small></td><td style={{padding:9}}>{l.extension_status||'—'}</td><td style={{padding:9}}>{l.overdue_at?'연체 '+new Date(l.overdue_at).toLocaleDateString('ko-KR'):l.status==='OVERDUE_REVIEW'?'협의 필요':'—'}</td><td style={{padding:9}}><button onClick={()=>setDetailLoan(l)} style={{height:30,padding:'0 9px',border:'1px solid #343a3e',borderRadius:6,background:'#171a1c',color:'#fff',fontSize:11,cursor:'pointer'}}>상세</button></td><td style={{padding:9}}>{v2Actions(l)}</td></tr>)}</tbody></table></div>
  {detailLoan&&<div style={{marginTop:14,padding:16,border:'1px solid #334047',borderRadius:10,background:'#0b1012'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><b style={{fontSize:16}}>대출 신청 상세 · {detailLoan.loan_no}</b><small style={{display:'block',color:'#738087',marginTop:4}}>{detailLoan.email||detailLoan.user_id}</small></div><button onClick={()=>setDetailLoan(null)} style={{border:0,background:'transparent',color:'#fff',fontSize:20,cursor:'pointer'}}>×</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:10,marginTop:14}}>{[['대출상품',detailLoan.product_name],['신청금액',Number(detailLoan.principal||0).toLocaleString()+' USDT'],['담보자산',(detailLoan.asset_symbol||detailLoan.collateral_asset)+' '+Number(detailLoan.collateral_locked_quantity||detailLoan.collateral_quantity||0).toLocaleString()],['신청 당시 담보가치',Number(detailLoan.initial_value||0).toLocaleString()+' USDT'],['현재 담보가치',Number(detailLoan.collateral_current_value||detailLoan.current_collateral_value||detailLoan.initial_value||0).toLocaleString()+' USDT'],['현재 LTV',detailLoan.current_ltv==null?'—':(Number(detailLoan.current_ltv)*100).toFixed(2)+'%'],['기본 이자율',(Number(detailLoan.interest_rate||0)*100).toFixed(2)+'%'],['상환기간',String(detailLoan.term_days||7)+'일'],['예정 만기일',detailLoan.due_at?new Date(detailLoan.due_at).toLocaleString('ko-KR'):'승인 후 확정'],['현재 계정 총자산',Number(detailLoan.account_total_value||0).toLocaleString()+' USDT'],['현재 전체 담보금액',Number(detailLoan.account_total_reserve||0).toLocaleString()+' USDT'],['승인 후 출금제한',Number(detailLoan.account_total_reserve||0).toLocaleString()+' USDT']].map(([k,v])=><div key={String(k)} style={{padding:11,border:'1px solid #263036',borderRadius:8,background:'#111719'}}><small style={{color:'#758086'}}>{k}</small><b style={{display:'block',marginTop:5}}>{String(v??'—')}</b></div>)}</div>{detailLoan.status==='PENDING'&&<div style={{display:'flex',gap:8,marginTop:14}}><button disabled={actionLoan===detailLoan.id||detailLoan.approval_available===false} onClick={()=>v2Approve(detailLoan)} style={{height:38,padding:'0 14px',border:0,borderRadius:7,background:'#b9ff31',fontWeight:900,cursor:'pointer'}}>대출 승인</button><button disabled={actionLoan===detailLoan.id} onClick={()=>v2Reject(detailLoan)} style={{height:38,padding:'0 14px',border:'1px solid #71323b',borderRadius:7,background:'#171a1c',color:'#ff8190',cursor:'pointer'}}>대출 거절</button>{detailLoan.approval_available===false&&<span style={{alignSelf:'center',color:'#ff8190',fontSize:11}}>현재 자산/담보 조건으로 승인할 수 없습니다.</span>}</div>}</div>}
 </section>
 <section style={{marginTop:16,padding:18,border:'1px solid #272c2f',borderRadius:14,background:'#111416'}}><h2 style={{fontSize:18,margin:'0 0 14px'}}>대출 신청 / 수동 처리</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12,minWidth:1050}}><thead><tr style={{color:'#758085'}}>{['Loan No','UID','담보','원금','LTV','상태','Provider','관리자 처리'].map(x=><th key={x} style={{textAlign:'left',padding:9}}>{x}</th>)}</tr></thead><tbody>{(snap.recent_loans||[]).map((l:Loan)=><tr key={l.id} style={{borderTop:'1px solid #23282b'}}><td style={{padding:10}}>{l.loan_no}</td><td style={{padding:10}}>{String(l.user_id).slice(0,8)}…</td><td style={{padding:10}}>{l.collateral_quantity} {l.collateral_asset}</td><td style={{padding:10}}>{l.principal} {l.borrow_asset}</td><td style={{padding:10}}>{l.current_ltv==null?'—':`${(Number(l.current_ltv)*100).toFixed(2)}%`}</td><td style={{padding:10}}><b>{l.status}</b><small style={{display:'block',color:'#687176',marginTop:3}}>{l.provider_status||''}</small></td><td style={{padding:10}}>{l.provider_loan_id||'—'}</td><td style={{padding:10}}>{actions(l)}</td></tr>)}</tbody></table></div></section>
 </div></main>
}