import {siteConfirm,sitePrompt} from './SiteDialog';
'use client';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';

type AppRow={id:string;user_id:string;tier_code:string;tier_name:string;full_name:string;email:string;phone:string|null;messenger:string|null;country:string|null;notes:string|null;btmt_amount:number;btmt_price_usdt:number;usdt_equivalent:number;status:string;admin_note:string|null;created_at:string};
type Snapshot={applications?:AppRow[];memberships?:any[];settings?:{btmt_price_usdt:number;support_email:string|null}};
export default function AdminBtmtMembershipClient(){
 const supabase=useMemo(()=>createBrowserSupabase(),[]);const [admin,setAdmin]=useState<boolean|null>(null);const [snap,setSnap]=useState<Snapshot>({});const [price,setPrice]=useState('0.6');const [email,setEmail]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);
 async function load(){const {data:{user}}=await supabase.auth.getUser();const ok=user?.app_metadata?.role==='admin';setAdmin(ok);if(!ok)return;const {data,error}=await supabase.rpc('admin_btmt_membership_snapshot');if(error){setMsg(error.message);return;}const s=(data||{}) as Snapshot;setSnap(s);setPrice(String(s.settings?.btmt_price_usdt??0.6));setEmail(s.settings?.support_email||'')}
 useEffect(()=>{load()},[]);
 async function saveSettings(){setBusy(true);setMsg('');const {error}=await supabase.rpc('admin_update_btmt_membership_settings',{p_price:Number(price),p_support_email:email||null});setBusy(false);if(error){setMsg(error.message);return;}setMsg('멤버십 설정이 저장되었습니다.');await load()}
 async function act(id:string,action:string){const note=(await sitePrompt(`${action} 처리 메모를 입력하세요.`,'',{title:'멤버십 처리 메모'}))||'';setBusy(true);setMsg('');const {error}=await supabase.rpc('admin_process_btmt_application',{p_application:id,p_action:action,p_note:note||null});setBusy(false);if(error){setMsg(error.message);return;}setMsg(`${action} 처리되었습니다.`);await load()}
 if(admin===null)return <main className="wrap"><p>Loading...</p></main>;if(!admin)return <main className="wrap"><div className="warning">관리자 권한이 필요합니다.</div></main>;
 return <main style={{minHeight:'calc(100vh - 72px)',background:'#0b0d0e',padding:'42px 0 90px',color:'#fff'}}><div className="xtShell"><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'end',marginBottom:20}}><div><span style={{color:'#b9ff31',fontSize:12,fontWeight:900,letterSpacing:'.14em'}}>BTMT MEMBERSHIP ADMIN</span><h1 style={{fontSize:40,margin:'8px 0 0'}}>Membership Control</h1></div></div>{msg&&<div style={{padding:12,border:'1px solid #4b4930',background:'#211f12',borderRadius:9,marginBottom:14,color:'#e4cf74'}}>{msg}</div>}
 <section style={{display:'grid',gridTemplateColumns:'360px 1fr',gap:14}}><div style={{padding:18,border:'1px solid #272c2f',borderRadius:14,background:'#111416'}}><h2 style={{fontSize:18,margin:'0 0 14px'}}>운영 설정</h2><label style={{display:'grid',gap:6,fontSize:11,color:'#828b90',marginBottom:12}}>BTMT 기준가 (USDT)<input value={price} onChange={e=>setPrice(e.target.value)} style={{height:40,border:'1px solid #30363a',background:'#181c1e',borderRadius:7,color:'#fff',padding:'0 10px'}}/></label><label style={{display:'grid',gap:6,fontSize:11,color:'#828b90',marginBottom:12}}>고객센터 이메일<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="support@example.com" style={{height:40,border:'1px solid #30363a',background:'#181c1e',borderRadius:7,color:'#fff',padding:'0 10px'}}/></label><button disabled={busy} onClick={saveSettings} style={{height:40,padding:'0 16px',border:0,borderRadius:7,background:'#b9ff31',fontWeight:900}}>설정 저장</button><p style={{fontSize:11,color:'#737c80',lineHeight:1.6,marginTop:14}}>고객센터 이메일을 설정하면 회원이 멤버십 신청서를 제출한 뒤 같은 내용으로 메일 작성 화면을 열 수 있습니다.</p></div>
 <div style={{padding:18,border:'1px solid #272c2f',borderRadius:14,background:'#111416'}}><h2 style={{fontSize:18,margin:'0 0 14px'}}>신청 현황</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr style={{color:'#758085'}}>{['신청일','회원','등급','BTMT','USDT 상당','상태','처리'].map(x=><th key={x} style={{textAlign:'left',padding:9}}>{x}</th>)}</tr></thead><tbody>{(snap.applications||[]).map(a=><tr key={a.id} style={{borderTop:'1px solid #23282b'}}><td style={{padding:10}}>{new Date(a.created_at).toLocaleDateString()}</td><td style={{padding:10}}><b>{a.full_name}</b><small style={{display:'block',color:'#778085'}}>{a.email}</small></td><td style={{padding:10}}>{a.tier_name}</td><td style={{padding:10}}>{Number(a.btmt_amount).toLocaleString()}</td><td style={{padding:10}}>{Number(a.usdt_equivalent).toLocaleString()} USDT</td><td style={{padding:10,color:a.status==='APPROVED'?'#b9ff31':'#fff'}}>{a.status}</td><td style={{padding:10}}><div style={{display:'flex',gap:5,flexWrap:'wrap'}}>{a.status!=='APPROVED'&&<><button onClick={()=>act(a.id,'CONTACTED')} disabled={busy}>연락완료</button><button onClick={()=>act(a.id,'APPROVED')} disabled={busy}>승인</button><button onClick={()=>act(a.id,'REJECTED')} disabled={busy}>거절</button><button onClick={()=>act(a.id,'CANCELED')} disabled={busy}>취소</button></>}</div></td></tr>)}</tbody></table></div></div></section>
 </div></main>
}
