'use client';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';

type Season={id:string;name:string;starts_at:string;ends_at:string;active:boolean};
type Prize={id:string;prize_name:string;amount:number;daily_limit:number|null;season_limit:number|null;enabled:boolean};
type Version={id:string;season_id:string;version_no:number;status:string;effective_from:string};
type Item={id:string;version_id:string;prize_id:string;probability:number};

export default function AdminLuckyDrawClient(){
 const supabase=useMemo(()=>createBrowserSupabase(),[]); const [admin,setAdmin]=useState<boolean|null>(null); const [snapshot,setSnapshot]=useState<any>(null); const [seasons,setSeasons]=useState<Season[]>([]); const [prizes,setPrizes]=useState<Prize[]>([]); const [versions,setVersions]=useState<Version[]>([]); const [items,setItems]=useState<Item[]>([]); const [selectedVersion,setSelectedVersion]=useState(''); const [msg,setMsg]=useState('');
 async function load(){setMsg('');const {data:{user}}=await supabase.auth.getUser();const ok=user?.app_metadata?.role==='admin';setAdmin(ok);if(!ok)return;const [{data:snap,error:se},{data:s},{data:p},{data:v},{data:i}]=await Promise.all([supabase.rpc('admin_lucky_draw_snapshot'),supabase.from('lucky_draw_seasons').select('*').order('starts_at',{ascending:false}),supabase.from('lucky_draw_prizes').select('*').order('sort_order'),supabase.from('lucky_draw_probability_versions').select('*').order('version_no',{ascending:false}),supabase.from('lucky_draw_probability_items').select('*')]);if(se)setMsg(se.message);setSnapshot(snap);setSeasons((s||[]) as Season[]);setPrizes((p||[]) as Prize[]);setVersions((v||[]) as Version[]);setItems((i||[]) as Item[]);if(!selectedVersion&&v?.[0])setSelectedVersion(v[0].id);}
 useEffect(()=>{load();},[]);
 async function createVersion(){const season=seasons.find(s=>s.active)||seasons[0];if(!season)return;const {data,error}=await supabase.rpc('admin_create_lucky_draw_version',{p_season:season.id,p_effective_from:new Date().toISOString()});if(error){setMsg(error.message);return;}setSelectedVersion(String(data));await load();}
 async function setProb(prizeId:string,value:string){if(!selectedVersion)return;const n=Number(value);if(!Number.isFinite(n))return;const {error}=await supabase.rpc('admin_set_lucky_draw_probability',{p_version:selectedVersion,p_prize:prizeId,p_probability:n});if(error){setMsg(error.message);return;}await load();}
 async function publish(){if(!selectedVersion)return;const {error}=await supabase.rpc('admin_publish_lucky_draw_version',{p_version:selectedVersion});if(error){setMsg(error.message);return;}setMsg('Probability Version이 발행되었습니다.');await load();}
 async function togglePrize(p:Prize){const {error}=await supabase.rpc('admin_update_lucky_draw_prize',{p_prize:p.id,p_enabled:!p.enabled,p_daily_limit:p.daily_limit,p_season_limit:p.season_limit});if(error){setMsg(error.message);return;}await load();}
 if(admin===null)return <main className="wrap"><p>Loading...</p></main>; if(!admin)return <main className="wrap"><div className="warning">관리자 권한이 필요합니다.</div></main>;
 const current=versions.find(v=>v.id===selectedVersion);const total=items.filter(i=>i.version_id===selectedVersion).reduce((s,x)=>s+Number(x.probability||0),0);
 return <main style={{minHeight:'calc(100vh - 72px)',background:'#0b0d0e',padding:'44px 0 90px'}}><div className="xtShell"><div style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'end',marginBottom:22}}><div><span style={{color:'#b9ff31',fontSize:12,fontWeight:900,letterSpacing:'.14em'}}>LUCKY DRAW ADMIN</span><h1 style={{fontSize:42,margin:'8px 0 0'}}>Lucky Draw Control</h1></div><button onClick={createVersion} style={{height:42,padding:'0 18px',border:0,borderRadius:9,background:'#b9ff31',fontWeight:900}}>새 Probability Version</button></div>{msg&&<div style={{padding:12,border:'1px solid #5a4420',background:'#241a0d',borderRadius:10,color:'#ffd483',marginBottom:14}}>{msg}</div>}
  <section style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:10,marginBottom:18}}>{[['오늘 Draw',snapshot?.stats?.today_draws||0],['누적 Draw',snapshot?.stats?.total_draws||0],['전체 발급 Ball',snapshot?.stats?.issued_balls||0],['미사용 Ball',snapshot?.stats?.available_balls||0],['미지급 Prize',snapshot?.stats?.pending_payouts||0]].map(([k,v])=><div key={String(k)} style={{padding:16,border:'1px solid #252a2d',borderRadius:13,background:'#111416'}}><small style={{color:'#788186'}}>{k}</small><b style={{display:'block',fontSize:21,marginTop:6}}>{String(v)}</b></div>)}</section>
  <section style={{display:'grid',gridTemplateColumns:'.75fr 1.25fr',gap:14}}><div style={{border:'1px solid #252a2d',background:'#111416',borderRadius:16,padding:18}}><h2 style={{fontSize:18,margin:'0 0 12px'}}>Probability Version</h2><select value={selectedVersion} onChange={e=>setSelectedVersion(e.target.value)} style={{width:'100%',height:42,background:'#1a1e20',border:'1px solid #30363a',borderRadius:8,color:'#fff',padding:'0 10px'}}>{versions.map(v=><option key={v.id} value={v.id}>v{v.version_no} · {v.status}</option>)}</select><div style={{marginTop:14,padding:13,background:'#181c1e',borderRadius:9}}><small style={{color:'#7f898e'}}>확률 합계</small><b style={{display:'block',fontSize:28,color:Math.abs(total-100)<0.000001?'#b9ff31':'#ff6d7f'}}>{total.toFixed(6)}%</b></div><button disabled={!selectedVersion||current?.status!=='DRAFT'} onClick={publish} style={{width:'100%',height:42,marginTop:12,border:0,borderRadius:8,background:'#f2f3f3',fontWeight:900,opacity:!selectedVersion||current?.status!=='DRAFT'?.4:1}}>100% 검증 후 발행</button><p style={{fontSize:11,color:'#737c80',lineHeight:1.6}}>발행된 Version은 기존 Draw에 그대로 보존됩니다. 다음 변경은 새 Version으로 생성하세요.</p></div>
   <div style={{border:'1px solid #252a2d',background:'#111416',borderRadius:16,padding:18}}><h2 style={{fontSize:18,margin:'0 0 12px'}}>Prize Table</h2><div style={{display:'grid',gap:7}}>{prizes.map(p=>{const it=items.find(i=>i.version_id===selectedVersion&&i.prize_id===p.id);return <div key={p.id} style={{display:'grid',gridTemplateColumns:'1fr 110px 92px',gap:8,alignItems:'center',padding:'11px 12px',border:'1px solid #24292c',borderRadius:10,background:'#171a1c'}}><div><b>{p.prize_name}</b><small style={{display:'block',color:'#727b80',marginTop:3}}>{Number(p.amount).toLocaleString()} USDT · {p.enabled?'ENABLED':'DISABLED'}</small></div><input disabled={!selectedVersion||current?.status!=='DRAFT'} defaultValue={it?.probability??0} onBlur={e=>setProb(p.id,e.target.value)} type="number" min="0" max="100" step="0.000001" style={{height:36,background:'#101315',border:'1px solid #30363a',borderRadius:7,color:'#fff',padding:'0 8px'}}/><button onClick={()=>togglePrize(p)} style={{height:36,border:'1px solid #343a3d',borderRadius:7,background:p.enabled?'#273117':'#1b1e20',color:p.enabled?'#b9ff31':'#b7bdc0',fontWeight:800}}>{p.enabled?'ON':'OFF'}</button></div>})}</div></div></section>
 </div></main>
}