'use client';

import {siteConfirm,sitePrompt} from './SiteDialog';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';
import s from './CfdTrading.module.css';
export default function AdminCfdClient(){
 const supabase=useMemo(()=>createBrowserSupabase(),[]);const [admin,setAdmin]=useState<boolean|null>(null);const [data,setData]=useState<any>({products:[],accounts:[],orders:[],positions:[],liquidations:[],settings:{}});const [msg,setMsg]=useState('');
 const [symbol,setSymbol]=useState(''),[name,setName]=useState(''),[category,setCategory]=useState('CRYPTO'),[source,setSource]=useState('BINANCE'),[levs,setLevs]=useState('1,2,3,5,10');
 async function load(){const {data:{user}}=await supabase.auth.getUser();const ok=user?.app_metadata?.role==='admin';setAdmin(ok);if(!ok)return;const {data:d,error}=await supabase.rpc('admin_get_cfd_dashboard');if(error)setMsg(error.message);else setData(d||{})}
 useEffect(()=>{load()},[]);
 async function createProduct(){setMsg('');const {error}=await supabase.rpc('admin_upsert_cfd_product',{p_id:null,p_symbol:symbol.trim().toUpperCase(),p_display_name:name.trim(),p_category:category,p_price_source:source,p_min_order:10,p_max_order:100000,p_available_leverages:levs.split(',').map(Number).filter(Boolean),p_maintenance_margin_rate:.1,p_trading_fee:.0005,p_liquidation_fee:.002,p_fixed_spread:0,p_spread_enabled:false,p_status:source==='MANUAL'?'PAUSED':'ACTIVE',p_trading_enabled:source!=='MANUAL'});if(error)setMsg(error.message);else{setMsg('CFD 상품이 등록되었습니다.');setSymbol('');setName('');await load()}}
 async function changeProduct(p:any,status:string){const {error}=await supabase.rpc('admin_upsert_cfd_product',{p_id:p.id,p_symbol:p.symbol,p_display_name:p.display_name,p_category:p.category,p_price_source:p.price_source,p_min_order:p.min_order,p_max_order:p.max_order,p_available_leverages:p.available_leverages,p_maintenance_margin_rate:p.maintenance_margin_rate,p_trading_fee:p.trading_fee,p_liquidation_fee:p.liquidation_fee,p_fixed_spread:p.fixed_spread,p_spread_enabled:p.spread_enabled,p_status:status,p_trading_enabled:status==='ACTIVE'});if(error)setMsg(error.message);else await load()}
 async function forceClose(id:string){const reason=await sitePrompt('강제 종료 사유를 입력하세요.','',{title:'CFD 강제 종료'});if(!reason)return;const {error}=await supabase.rpc('admin_force_close_cfd_position',{p_position_id:id,p_reason:reason});if(error)setMsg(error.message);else{setMsg('관리자 강제종료가 처리되었습니다.');await load()}}
 if(admin===null)return <main className={s.page}><div className={s.shell}><p>관리자 권한 확인 중...</p></div></main>;
 if(!admin)return <main className={s.page}><div className={s.shell}><p>관리자 권한이 필요합니다.</p></div></main>;
 return <main className={s.page}><section className={`${s.shell} ${s.hero}`}><div><span className={s.eyebrow}>ADMIN · CFD</span><h1>CFD Management</h1><p>상품·레버리지·수수료·포지션·강제청산 상태를 관리합니다. 손익 직접 입력 기능은 제공하지 않습니다.</p></div><div className={s.status}><span className={s.pill}>CFD {String(data.settings?.CFD_ENABLED)}</span><span className={s.pill}>REAL {String(data.settings?.CFD_REAL_ENABLED)}</span></div></section>{msg&&<section className={s.shell}><div className={s.warning}>{msg}</div></section>}
 <section className={`${s.shell} ${s.adminGrid}`}><div className={s.panel}><div className={s.panelHead}><b>상품 등록</b></div><div className={s.panelBody}><label className={s.field}>Symbol<input value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="BTCUSDT"/></label><label className={s.field}>Display Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="BTC/USDT"/></label><label className={s.field}>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>CRYPTO</option><option>METAL</option><option>ENERGY</option><option>INDEX</option><option>FOREX</option></select></label><label className={s.field}>Price Source<select value={source} onChange={e=>setSource(e.target.value)}><option>BINANCE</option><option>MANUAL</option></select></label><label className={s.field}>Leverages<input value={levs} onChange={e=>setLevs(e.target.value)}/></label><button className={s.primary} onClick={createProduct}>Add CFD Product</button></div></div>
 <div className={s.panel}><div className={s.panelHead}><b>Products</b><span>{data.products?.length||0}</span></div><div className={s.panelBody}>{(data.products||[]).map((p:any)=><div className={s.adminItem} key={p.id}><b>{p.display_name} · {p.symbol}</b><small>{p.category} · {p.price_source} · {p.available_leverages?.join('/')}X · fee {(Number(p.trading_fee)*100).toFixed(3)}%</small><select value={p.status} onChange={e=>changeProduct(p,e.target.value)}><option>ACTIVE</option><option>CLOSE_ONLY</option><option>PAUSED</option><option>CLOSED</option></select></div>)}</div></div></section>
 <section className={`${s.shell} ${s.section}`}><div className={s.panel}><div className={s.panelHead}><b>Open / Recent Positions</b><span>{data.positions?.length||0}</span></div><div className={s.tableWrap}><table className={s.table}><thead><tr><th>UID</th><th>Symbol</th><th>Side</th><th>Margin</th><th>Lev</th><th>Entry</th><th>Current</th><th>PnL</th><th>Status</th><th></th></tr></thead><tbody>{(data.positions||[]).map((p:any)=><tr key={p.id}><td>{p.user_id.slice(0,8)}…</td><td>{p.symbol}</td><td>{p.side}</td><td>{Number(p.remaining_margin).toFixed(2)}</td><td>{p.leverage}X</td><td>{Number(p.entry_price).toFixed(2)}</td><td>{Number(p.current_price).toFixed(2)}</td><td>{Number(p.unrealized_pnl).toFixed(2)}</td><td>{p.status}</td><td>{['OPEN','PARTIALLY_CLOSED'].includes(p.status)&&<button className={s.ghost} onClick={()=>forceClose(p.id)}>Force Close</button>}</td></tr>)}</tbody></table></div></div></section>
 <section className={`${s.shell} ${s.section}`}><div className={s.panel}><div className={s.panelHead}><b>Recent Orders</b><span>{data.orders?.length||0}</span></div><div className={s.tableWrap}><table className={s.table}><thead><tr><th>UID</th><th>Order ID</th><th>Symbol</th><th>Side</th><th>Margin</th><th>Lev</th><th>Exec Price</th><th>Fee</th><th>Status</th></tr></thead><tbody>{(data.orders||[]).map((o:any)=><tr key={o.id}><td>{o.user_id.slice(0,8)}…</td><td>{o.id.slice(0,8)}…</td><td>{o.symbol}</td><td>{o.side}</td><td>{Number(o.margin).toFixed(2)}</td><td>{o.leverage}X</td><td>{o.execution_price?Number(o.execution_price).toFixed(2):'—'}</td><td>{Number(o.fee).toFixed(4)}</td><td>{o.status}</td></tr>)}</tbody></table></div></div></section>
 <section className={`${s.shell} ${s.section}`}><div className={s.panel}><div className={s.panelHead}><b>Liquidation History</b><span>{data.liquidations?.length||0}</span></div><div className={s.tableWrap}><table className={s.table}><thead><tr><th>UID</th><th>Position</th><th>Trigger</th><th>Execution</th><th>Realized PnL</th><th>Fee</th><th>Time</th></tr></thead><tbody>{(data.liquidations||[]).map((x:any)=><tr key={x.id}><td>{x.user_id.slice(0,8)}…</td><td>{x.position_id.slice(0,8)}…</td><td>{Number(x.trigger_price).toFixed(2)}</td><td>{Number(x.execution_price).toFixed(2)}</td><td>{Number(x.realized_pnl).toFixed(2)}</td><td>{Number(x.liquidation_fee).toFixed(2)}</td><td>{new Date(x.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></div></section>
 </main>;
}
