'use client';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';

type Product={id:string;name:string;borrow_asset:string;collateral_asset:string;term_mode:string;term_days:number|null;hourly_rate:number|null;annual_rate:number|null;initial_ltv:number;margin_call_ltv:number;liquidation_ltv:number;min_borrow:number;max_borrow:number|null;provider_code:string|null;provider_product_code:string|null;status:string;visible:boolean;sort_order:number};
type Snapshot={counts?:Record<string,number>;principal_active?:number;interest_accrued?:number;products?:Product[];recent_loans?:any[]};
const empty={id:'',name:'',borrow_asset:'USDT',collateral_asset:'BTC',term_mode:'FLEXIBLE',term_days:'',hourly_rate:'',annual_rate:'',initial_ltv:'0.65',margin_call_ltv:'0.75',liquidation_ltv:'0.85',min_borrow:'100',max_borrow:'',provider_code:'',provider_product_code:'',status:'DRAFT',visible:false,sort_order:'100'};
export default function AdminCryptoLoanClient(){
 const supabase=useMemo(()=>createBrowserSupabase(),[]);const [admin,setAdmin]=useState<boolean|null>(null);const [snap,setSnap]=useState<Snapshot>({});const [form,setForm]=useState<any>(empty);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);
 async function load(){setMsg('');const {data:{user}}=await supabase.auth.getUser();const ok=user?.app_metadata?.role==='admin';setAdmin(ok);if(!ok)return;const {data,error}=await supabase.rpc('admin_crypto_loan_snapshot');if(error)setMsg(error.message);setSnap((data||{}) as Snapshot)}
 useEffect(()=>{load()},[]);
 function edit(p:Product){setForm({...p,term_days:p.term_days??'',hourly_rate:p.hourly_rate??'',annual_rate:p.annual_rate??'',max_borrow:p.max_borrow??'',provider_code:p.provider_code??'',provider_product_code:p.provider_product_code??'',sort_order:String(p.sort_order)})}
 async function save(){setBusy(true);setMsg('');const {error}=await supabase.rpc('admin_upsert_crypto_loan_product',{p_id:form.id||null,p_name:form.name,p_borrow_asset:form.borrow_asset,p_collateral_asset:form.collateral_asset,p_term_mode:form.term_mode,p_term_days:form.term_mode==='FIXED'?Number(form.term_days):null,p_hourly_rate:Number(form.hourly_rate),p_annual_rate:form.annual_rate===''?null:Number(form.annual_rate),p_initial_ltv:Number(form.initial_ltv),p_margin_call_ltv:Number(form.margin_call_ltv),p_liquidation_ltv:Number(form.liquidation_ltv),p_min_borrow:Number(form.min_borrow||0),p_max_borrow:form.max_borrow===''?null:Number(form.max_borrow),p_provider_code:form.provider_code||null,p_provider_product_code:form.provider_product_code||null,p_status:form.status,p_visible:!!form.visible,p_sort_order:Number(form.sort_order||100)});setBusy(false);if(error){setMsg(error.message);return;}setMsg('대출 상품이 저장되었습니다.');setForm(empty);await load()}
 if(admin===null)return <main className="wrap"><p>Loading...</p></main>;if(!admin)return <main className="wrap"><div className="warning">관리자 권한이 필요합니다.</div></main>;
 const c=snap.counts||{};return <main style={{minHeight:'calc(100vh - 72px)',background:'#0b0d0e',padding:'42px 0 90px',color:'#fff'}}><div className="xtShell"><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'end',marginBottom:20}}><div><span style={{color:'#b9ff31',fontSize:12,fontWeight:900,letterSpacing:'.14em'}}>CRYPTO LOAN ADMIN</span><h1 style={{fontSize:40,margin:'8px 0 0'}}>Collateral Loan Control</h1></div></div>{msg&&<div style={{padding:12,border:'1px solid #4b4930',background:'#211f12',borderRadius:9,marginBottom:14,color:'#e4cf74'}}>{msg}</div>}
 <section style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:9,marginBottom:16}}>{[['신청 대기',c.requested||0],['활성',c.active||0],['Margin Call',c.margin_call||0],['청산 대기',c.liquidation_pending||0],['활성 원금',Number(snap.principal_active||0).toLocaleString()],['누적 이자',Number(snap.interest_accrued||0).toLocaleString()]].map(([k,v])=><div key={String(k)} style={{padding:14,border:'1px solid #272c2f',borderRadius:11,background:'#111416'}}><small style={{color:'#788186'}}>{k}</small><b style={{display:'block',fontSize:18,marginTop:6}}>{String(v)}</b></div>)}</section>
 <section style={{display:'grid',gridTemplateColumns:'.85fr 1.15fr',gap:14}}><div style={{padding:18,border:'1px solid #272c2f',borderRadius:14,background:'#111416'}}><h2 style={{fontSize:18,margin:'0 0 14px'}}>{form.id?'상품 수정':'새 상품'}</h2><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:9}}>{[['name','상품명'],['borrow_asset','대출 자산'],['collateral_asset','담보 자산'],['hourly_rate','시간당 금리(소수)'],['annual_rate','연 이자율(소수)'],['initial_ltv','초기 LTV'],['margin_call_ltv','마진콜 LTV'],['liquidation_ltv','청산 LTV'],['min_borrow','최소 대출'],['max_borrow','최대 대출'],['provider_code','Provider 코드'],['provider_product_code','Provider 상품코드'],['sort_order','정렬순서']].map(([key,label])=><label key={key} style={{display:'grid',gap:5,fontSize:11,color:'#828b90'}}>{label}<input value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} style={{height:38,border:'1px solid #30363a',background:'#181c1e',borderRadius:7,color:'#fff',padding:'0 9px'}}/></label>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:9,marginTop:9}}><label style={{display:'grid',gap:5,fontSize:11,color:'#828b90'}}>기간<select value={form.term_mode} onChange={e=>setForm({...form,term_mode:e.target.value})} style={{height:38,background:'#181c1e',color:'#fff',border:'1px solid #30363a',borderRadius:7}}><option value="FLEXIBLE">FLEXIBLE</option><option value="FIXED">FIXED</option></select></label><label style={{display:'grid',gap:5,fontSize:11,color:'#828b90'}}>기간(일)<input disabled={form.term_mode!=='FIXED'} value={form.term_days} onChange={e=>setForm({...form,term_days:e.target.value})} style={{height:38,border:'1px solid #30363a',background:'#181c1e',borderRadius:7,color:'#fff',padding:'0 9px'}}/></label><label style={{display:'grid',gap:5,fontSize:11,color:'#828b90'}}>상태<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} style={{height:38,background:'#181c1e',color:'#fff',border:'1px solid #30363a',borderRadius:7}}>{['DRAFT','ACTIVE','PAUSED','DISABLED'].map(x=><option key={x}>{x}</option>)}</select></label></div><label style={{display:'flex',gap:8,margin:'12px 0',fontSize:12}}><input type="checkbox" checked={!!form.visible} onChange={e=>setForm({...form,visible:e.target.checked})}/>회원 화면 노출</label><div style={{display:'flex',gap:8}}><button disabled={busy} onClick={save} style={{height:40,padding:'0 16px',border:0,borderRadius:7,background:'#b9ff31',fontWeight:900}}>{busy?'저장 중...':'저장'}</button>{form.id&&<button onClick={()=>setForm(empty)} style={{height:40,padding:'0 16px',border:'1px solid #30363a',borderRadius:7,background:'#171a1c',color:'#fff'}}>새 상품</button>}</div></div>
 <div style={{padding:18,border:'1px solid #272c2f',borderRadius:14,background:'#111416'}}><h2 style={{fontSize:18,margin:'0 0 14px'}}>상품 목록</h2><div style={{display:'grid',gap:8}}>{(snap.products||[]).map(p=><button key={p.id} onClick={()=>edit(p)} style={{textAlign:'left',padding:12,border:'1px solid #262b2e',borderRadius:9,background:'#171a1c',color:'#fff',cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><b>{p.name}</b><span style={{color:p.status==='ACTIVE'?'#b9ff31':'#8a9296'}}>{p.status}{p.visible?' · VISIBLE':''}</span></div><small style={{display:'block',marginTop:5,color:'#788186'}}>{p.collateral_asset} → {p.borrow_asset} · {p.term_mode}{p.term_days?` ${p.term_days}D`:''} · Hourly {Number(p.hourly_rate||0)} · LTV {Number(p.initial_ltv)*100}%/{Number(p.margin_call_ltv)*100}%/{Number(p.liquidation_ltv)*100}%</small></button>)}</div></div></section>
 <section style={{marginTop:16,padding:18,border:'1px solid #272c2f',borderRadius:14,background:'#111416'}}><h2 style={{fontSize:18,margin:'0 0 14px'}}>최근 대출 신청</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr style={{color:'#758085'}}>{['Loan No','UID','담보','원금','LTV','상태','Provider Loan'].map(x=><th key={x} style={{textAlign:'left',padding:9}}>{x}</th>)}</tr></thead><tbody>{(snap.recent_loans||[]).map((l:any)=><tr key={l.id} style={{borderTop:'1px solid #23282b'}}><td style={{padding:10}}>{l.loan_no}</td><td style={{padding:10}}>{String(l.user_id).slice(0,8)}…</td><td style={{padding:10}}>{l.collateral_quantity} {l.collateral_asset}</td><td style={{padding:10}}>{l.principal} {l.borrow_asset}</td><td style={{padding:10}}>{l.current_ltv==null?'—':`${(Number(l.current_ltv)*100).toFixed(2)}%`}</td><td style={{padding:10}}>{l.status}</td><td style={{padding:10}}>{l.provider_loan_id||'—'}</td></tr>)}</tbody></table></div></section>
 </div></main>
}