'use client';

import {siteConfirm,sitePrompt} from './SiteDialog';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';
import s from '@/app/crypto-etf/Index.module.css';
export default function AdminIndexClient(){
 const supabase=useMemo(()=>createBrowserSupabase(),[]);const [admin,setAdmin]=useState<boolean|null>(null),[products,setProducts]=useState<any[]>([]),[msg,setMsg]=useState('');
 async function load(){const {data:{user}}=await supabase.auth.getUser();const ok=user?.app_metadata?.role==='admin';setAdmin(ok);if(!ok)return;const {data}=await supabase.from('index_products').select('*').order('sort_order');setProducts(data||[])}
 useEffect(()=>{load()},[]);
 async function save(p:any){const {error}=await supabase.rpc('admin_update_index_product',{p_product_id:p.id,p_status:p.status,p_visible:p.visible,p_rebalance_frequency:p.rebalance_frequency,p_rebalance_threshold:Number(p.rebalance_threshold),p_entry_fee_rate:Number(p.entry_fee_rate),p_exit_fee_rate:Number(p.exit_fee_rate),p_reason:'관리자 INDEX 설정 변경'});if(error)setMsg(error.message);else{setMsg('상품 설정이 저장되었습니다.');await load()}}
 async function rebalance(id:string){if(!(await siteConfirm('이 상품의 ACTIVE 포지션을 현재 목표비중으로 리밸런싱하시겠습니까?',{title:'리밸런싱 확인'})))return;const {error}=await supabase.rpc('admin_run_index_rebalance',{p_product_id:id,p_reason:'관리자 수동 리밸런싱'});if(error)setMsg(error.message);else setMsg('리밸런싱이 완료되었습니다.')}
 if(admin===null)return <main className={s.page}><div className={s.shell}><div className={s.empty}>관리자 권한 확인 중…</div></div></main>;
 if(!admin)return <main className={s.page}><div className={s.shell}><div className={s.empty}>관리자 권한이 필요합니다.</div></div></main>;
 return <main className={s.page}><section className={`${s.shell} ${s.hero}`}><span className={s.eyebrow}>ADMIN · BITMATE INDEX</span><h1>INDEX 관리</h1><p>상품 상태, 리밸런싱 정책, 수수료를 관리합니다. 회원별 ROI를 직접 수정하는 기능은 제공하지 않습니다.</p></section>{msg&&<section className={s.shell}><div className={s.warning}>{msg}</div></section>}<section className={`${s.shell} ${s.section}`}><div className={s.adminGrid}>{products.map((p,i)=><div className={s.panel} key={p.id}><div className={s.detailBlock}><div className={s.cardTop}><div><h3>{p.name}</h3><span className={s.muted}>{p.code}</span></div><span className={s.risk}>{p.risk_level}</span></div><label className={s.field}>Status<select value={p.status} onChange={e=>setProducts(x=>x.map((q,j)=>j===i?{...q,status:e.target.value}:q))}><option>ACTIVE</option><option>CLOSE_ONLY</option><option>PAUSED</option><option>DISABLED</option></select></label><label className={s.field}>Rebalance<select value={p.rebalance_frequency} onChange={e=>setProducts(x=>x.map((q,j)=>j===i?{...q,rebalance_frequency:e.target.value}:q))}><option>NONE</option><option>DAILY</option><option>WEEKLY</option><option>MONTHLY</option><option>MANUAL</option></select></label><label className={s.field}>Threshold<input value={p.rebalance_threshold} onChange={e=>setProducts(x=>x.map((q,j)=>j===i?{...q,rebalance_threshold:e.target.value}:q))}/></label><label className={s.field}>Entry Fee<input value={p.entry_fee_rate} onChange={e=>setProducts(x=>x.map((q,j)=>j===i?{...q,entry_fee_rate:e.target.value}:q))}/></label><label className={s.field}>Exit Fee<input value={p.exit_fee_rate} onChange={e=>setProducts(x=>x.map((q,j)=>j===i?{...q,exit_fee_rate:e.target.value}:q))}/></label><label className={s.check}><input type="checkbox" checked={!!p.visible} onChange={e=>setProducts(x=>x.map((q,j)=>j===i?{...q,visible:e.target.checked}:q))}/><span>회원 화면 노출</span></label><div className={s.modalActions}><button className={s.ghost} onClick={()=>rebalance(p.id)}>수동 리밸런싱</button><button className={s.btn} onClick={()=>save(p)}>저장</button></div></div></div>)}</div></section></main>
}
