'use client';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';
import s from './CfdTrading.module.css';

type Product={id:string;symbol:string;display_name:string;category:string;current_price:number|null;bid:number|null;ask:number|null;available_leverages:number[];maintenance_margin_rate:number;trading_fee:number;status:string;trading_enabled:boolean;last_price_at:string|null};
type Position={id:string;symbol:string;side:string;status:string;leverage:number;initial_margin:number;remaining_margin:number;position_value:number;remaining_quantity:number;entry_price:number;current_price:number;liquidation_price:number|null;stop_loss:number|null;take_profit:number|null;unrealized_pnl:number;realized_pnl:number;opened_at:string};

export default function CfdTradingClient(){
 const supabase=useMemo(()=>createBrowserSupabase(),[]);
 const [products,setProducts]=useState<Product[]>([]),[positions,setPositions]=useState<Position[]>([]),[closed,setClosed]=useState<Position[]>([]);
 const [selected,setSelected]=useState<Product|null>(null),[side,setSide]=useState<'LONG'|'SHORT'>('LONG'),[margin,setMargin]=useState('100'),[lev,setLev]=useState(1),[sl,setSl]=useState(''),[tp,setTp]=useState(''),[summary,setSummary]=useState<any>(null),[msg,setMsg]=useState('');
 async function load(){
  const {data:{user}}=await supabase.auth.getUser();
  const {data:p}=await supabase.from('cfd_products').select('*').order('sort_order'); setProducts((p||[]) as Product[]); if(!selected&&p?.[0]){setSelected(p[0] as Product);setLev((p[0] as any).available_leverages?.[0]||1)}
  if(!user)return;
  await supabase.rpc('ensure_cfd_demo_account');
  const [{data:pos},{data:sum}]=await Promise.all([supabase.from('cfd_positions').select('*').order('created_at',{ascending:false}),supabase.rpc('get_cfd_account_summary')]);
  const all=(pos||[]) as Position[]; setPositions(all.filter(x=>['OPEN','PARTIALLY_CLOSED'].includes(x.status)));setClosed(all.filter(x=>['CLOSED','LIQUIDATED'].includes(x.status)));setSummary(sum);
 }
 useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(selected&&!selected.available_leverages.includes(lev))setLev(selected.available_leverages[0]||1)},[selected]);
 const m=Number(margin)||0, px=side==='LONG'?(selected?.ask||selected?.current_price||0):(selected?.bid||selected?.current_price||0), posVal=m*lev, fee=selected?posVal*Number(selected.trading_fee):0;
 const liq=selected&&px&&lev?(side==='LONG'?px*(1-1/lev+Number(selected.maintenance_margin_rate)):px*(1+1/lev-Number(selected.maintenance_margin_rate))):0;
 async function order(){setMsg('');if(!selected){setMsg('상품을 선택하세요.');return;}if(m<=0){setMsg('증거금을 확인하세요.');return;}const riskVersion='cfd-risk-v1';const {data:{user}}=await supabase.auth.getUser();if(!user){setMsg('로그인이 필요합니다.');return;}await supabase.from('cfd_risk_acceptances').upsert({user_id:user.id,version:riskVersion},{onConflict:'user_id,version'});const id=crypto.randomUUID();const {error}=await supabase.rpc('open_cfd_market_order',{p_symbol:selected.symbol,p_side:side,p_margin:m,p_leverage:lev,p_stop_loss:sl?Number(sl):null,p_take_profit:tp?Number(tp):null,p_client_order_id:id,p_idempotency_key:id});if(error){setMsg(error.message);return;}setMsg('CFD 시장가 주문이 체결되었습니다.');await load()}
 async function close(id:string,pct:number){if(!confirm(`${pct}% 청산하시겠습니까?`))return;const {error}=await supabase.rpc('close_cfd_position',{p_position_id:id,p_percent:pct});if(error)setMsg(error.message);else{setMsg('청산이 반영되었습니다.');await load()}}
 async function updateStops(p:Position){const nsl=prompt('Stop Loss',p.stop_loss?.toString()||'')??'';const ntp=prompt('Take Profit',p.take_profit?.toString()||'')??'';const {error}=await supabase.rpc('update_cfd_sltp',{p_position_id:p.id,p_stop_loss:nsl?Number(nsl):null,p_take_profit:ntp?Number(ntp):null});if(error)setMsg(error.message);else await load()}
 return <main className={s.page}><section className={`${s.shell} ${s.hero}`}><div><span className={s.eyebrow}>CFD MARGIN · DEMO</span><h1>CFD Margin Trading</h1><p>차트 없이 주문·증거금·레버리지·포지션·손익·리스크 관리에 집중한 CFD 거래 화면입니다.</p></div><div className={s.status}><span className={s.pill}>ISOLATED</span><span className={s.pill}>MARKET</span><span className={s.pill}>REAL OFF</span></div></section>{msg&&<section className={s.shell}><div className={s.warning}>{msg}</div></section>}
 <section className={s.shell}><div className={s.summary}>{[['Wallet',summary?.wallet_balance],['Available',summary?.available_balance],['Used Margin',summary?.used_margin],['Unrealized PnL',summary?.unrealized_pnl],['Equity',summary?.equity],['Margin Level',summary?.margin_level==null?'N/A':`${Number(summary.margin_level).toFixed(2)}%`]].map(([k,v])=><div key={k as string}><span>{k}</span><b>{typeof v==='number'?Number(v).toFixed(2):v??'—'}</b></div>)}</div></section>
 <section className={`${s.shell} ${s.grid}`}><div className={s.panel}><div className={s.panelHead}><b>CFD Products</b><span className={s.muted}>현재가 기반 · 차트 제외</span></div><div className={s.panelBody}><div className={s.productList}>{products.map(p=><button key={p.id} onClick={()=>{setSelected(p);setLev(p.available_leverages?.[0]||1)}} className={`${s.product} ${selected?.id===p.id?s.active:''}`}><b>{p.display_name}</b><span>{p.current_price?Number(p.current_price).toLocaleString():'PRICE N/A'} · {p.status}</span></button>)}</div></div></div>
 <div className={s.panel}><div className={s.panelHead}><b>Order</b><span>{selected?.display_name||'—'}</span></div><div className={s.panelBody}><div className={s.sideRow}><button onClick={()=>setSide('LONG')} className={`${s.long} ${side==='LONG'?s.active:''}`}>LONG 상승</button><button onClick={()=>setSide('SHORT')} className={`${s.short} ${side==='SHORT'?s.active:''}`}>SHORT 하락</button></div><label className={s.field}>Margin (USDT)<input value={margin} onChange={e=>setMargin(e.target.value)} inputMode="decimal"/></label><label className={s.field}>Leverage<div className={s.leverages}>{(selected?.available_leverages||[1]).map(x=><button type="button" className={lev===x?s.active:''} onClick={()=>setLev(x)} key={x}>{x}X</button>)}</div></label><label className={s.field}>Stop Loss<input value={sl} onChange={e=>setSl(e.target.value)} placeholder="Optional"/></label><label className={s.field}>Take Profit<input value={tp} onChange={e=>setTp(e.target.value)} placeholder="Optional"/></label><div className={s.preview}><div><span>Position Value</span><b>{posVal.toFixed(2)} USDT</b></div><div><span>Estimated Entry</span><b>{px?Number(px).toLocaleString():'—'}</b></div><div><span>Estimated Fee</span><b>{fee.toFixed(4)} USDT</b></div><div><span>Estimated Liquidation</span><b>{liq?liq.toFixed(2):'—'}</b></div></div><button className={s.primary} onClick={order}>Place {side} Market Order</button></div></div></section>
 <section className={`${s.shell} ${s.section}`}><div className={s.panel}><div className={s.panelHead}><b>Open Positions</b><span>{positions.length}</span></div><div className={s.tableWrap}><table className={s.table}><thead><tr><th>Symbol</th><th>Side</th><th>Margin</th><th>Lev</th><th>Entry</th><th>Current</th><th>PnL</th><th>ROI</th><th>Liq.</th><th>SL / TP</th><th></th></tr></thead><tbody>{positions.length?positions.map(p=>{const roi=Number(p.remaining_margin)?Number(p.unrealized_pnl)/Number(p.remaining_margin)*100:0;return <tr key={p.id}><td>{p.symbol}</td><td className={p.side==='LONG'?s.pos:s.neg}>{p.side}</td><td>{Number(p.remaining_margin).toFixed(2)}</td><td>{p.leverage}X</td><td>{Number(p.entry_price).toFixed(2)}</td><td>{Number(p.current_price).toFixed(2)}</td><td className={Number(p.unrealized_pnl)>=0?s.pos:s.neg}>{Number(p.unrealized_pnl).toFixed(2)}</td><td>{roi.toFixed(2)}%</td><td>{p.liquidation_price?Number(p.liquidation_price).toFixed(2):'—'}</td><td>{p.stop_loss||'—'} / {p.take_profit||'—'}</td><td><div className={s.actions}><button className={s.ghost} onClick={()=>updateStops(p)}>SL/TP</button><button className={s.ghost} onClick={()=>close(p.id,25)}>25%</button><button className={s.ghost} onClick={()=>close(p.id,50)}>50%</button><button className={s.ghost} onClick={()=>close(p.id,100)}>Close</button></div></td></tr>}):<tr><td colSpan={11}>열린 포지션이 없습니다.</td></tr>}</tbody></table></div></div></section>
 <section className={`${s.shell} ${s.section}`}><div className={s.panel}><div className={s.panelHead}><b>Closed Positions</b><span>{closed.length}</span></div><div className={s.tableWrap}><table className={s.table}><thead><tr><th>Symbol</th><th>Side</th><th>Margin</th><th>Lev</th><th>Entry</th><th>Exit</th><th>Realized PnL</th><th>Reason</th><th>Opened</th></tr></thead><tbody>{closed.length?closed.map(p=><tr key={p.id}><td>{p.symbol}</td><td>{p.side}</td><td>{Number(p.initial_margin).toFixed(2)}</td><td>{p.leverage}X</td><td>{Number(p.entry_price).toFixed(2)}</td><td>{Number(p.current_price).toFixed(2)}</td><td className={Number(p.realized_pnl)>=0?s.pos:s.neg}>{Number(p.realized_pnl).toFixed(2)}</td><td>{(p as any).close_reason||'—'}</td><td>{new Date(p.opened_at).toLocaleString()}</td></tr>):<tr><td colSpan={9}>종료 포지션이 없습니다.</td></tr>}</tbody></table></div></div></section>
 </main>;
}
