import {siteConfirm,sitePrompt} from './SiteDialog';
'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {createBrowserSupabase} from '@/lib/supabase-browser';
import s from './CryptoLoan.module.css';

type Product={id:string;name:string;borrow_asset:string;collateral_asset:string;term_mode:'FLEXIBLE'|'FIXED';term_days:number|null;hourly_rate:number|null;annual_rate:number|null;initial_ltv:number;margin_call_ltv:number;liquidation_ltv:number;min_borrow:number;max_borrow:number|null};
type Loan={id:string;loan_no:string;borrow_asset:string;collateral_asset:string;principal:number;collateral_quantity:number;current_ltv:number|null;accrued_interest:number;repaid_principal:number;repaid_interest:number;status:string;created_at:string;due_at:string|null};
type Quote={product_id:string;borrow_asset:string;collateral_asset:string;principal:number;collateral_price:number;required_collateral:number;hourly_rate:number;annual_rate:number|null;initial_ltv:number;margin_call_ltv:number;liquidation_ltv:number;term_mode:string;term_days:number|null;estimated_interest:number;estimate_hours:number};

const fmt=(n:number,d=4)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(Number(n||0));
const pct=(n:number|null|undefined)=>n==null?'—':`${(Number(n)*100).toFixed(2)}%`;

export default function CryptoLoanClient(){
 const supabase=useMemo(()=>createBrowserSupabase(),[]);
 const [products,setProducts]=useState<Product[]>([]); const [loans,setLoans]=useState<Loan[]>([]); const [logged,setLogged]=useState(false); const [loading,setLoading]=useState(true);
 const [selected,setSelected]=useState<Product|null>(null); const [principal,setPrincipal]=useState(''); const [collateral,setCollateral]=useState(''); const [quote,setQuote]=useState<Quote|null>(null); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState(''); const [agree,setAgree]=useState(false);
 async function load(){setLoading(true); const [{data:p},{data:{user}}]=await Promise.all([supabase.from('crypto_loan_products').select('*').eq('status','ACTIVE').eq('visible',true).order('sort_order'),supabase.auth.getUser()]); setProducts((p||[]) as Product[]); setLogged(!!user); if(user){const {data:l}=await supabase.from('crypto_loans').select('id,loan_no,borrow_asset,collateral_asset,principal,collateral_quantity,current_ltv,accrued_interest,repaid_principal,repaid_interest,status,created_at,due_at').order('created_at',{ascending:false}).limit(30); setLoans((l||[]) as Loan[])}else setLoans([]); setLoading(false)}
 useEffect(()=>{load()},[]);
 async function openApply(p:Product){setSelected(p);setPrincipal(String(Math.max(Number(p.min_borrow||0),100)));setCollateral('');setQuote(null);setMsg('');setAgree(false);}
 async function calc(){if(!selected)return;const n=Number(principal);if(!Number.isFinite(n)||n<=0)return;setBusy(true);setMsg('');const {data,error}=await supabase.rpc('get_crypto_loan_quote',{p_product:selected.id,p_principal:n});setBusy(false);if(error){setMsg(error.message);return;}const q=data as Quote;setQuote(q);setCollateral(String(Number(q.required_collateral).toFixed(8)));}
 async function apply(){if(!selected||!quote||!agree)return;setBusy(true);setMsg('');const {error}=await supabase.rpc('apply_crypto_loan',{p_product:selected.id,p_principal:Number(principal),p_collateral_quantity:Number(collateral),p_idempotency_key:`loan:${crypto.randomUUID()}`});setBusy(false);if(error){setMsg(error.message);return;}setMsg('대출 신청이 접수되었습니다. 심사 완료 후 대출이 실행됩니다.');await load();setTimeout(()=>setSelected(null),900)}
 async function requestRepayment(l:Loan){const outstanding=Math.max(Number(l.principal)-Number(l.repaid_principal||0),0)+Math.max(Number(l.accrued_interest||0)-Number(l.repaid_interest||0),0);if(!(await siteConfirm(`${fmt(outstanding,6)} ${l.borrow_asset} 전액 상환 요청을 접수하시겠습니까?`,{title:'대출 상환 요청'})))return;setBusy(true);setMsg('');const {error}=await supabase.rpc('request_crypto_loan_repayment',{p_loan:l.id,p_amount:outstanding,p_idempotency_key:`repay:${crypto.randomUUID()}`});setBusy(false);if(error){setMsg(error.message);return;}setMsg('상환 요청이 접수되었습니다. 상환이 완료되면 담보 반환이 진행됩니다.');await load()}
 return <main className={s.page}>
  <section className={s.hero}><div className={s.shell}><div className={s.heroGrid}><div><span className={s.kicker}>CRYPTO COLLATERAL LOAN</span><h1 className={s.title}>보유 자산을 팔지 않고<br/>유동성을 확보하세요.</h1><p className={s.lead}>보유 암호화폐를 담보로 설정하고 상품별 금리·기간·LTV 기준에 따라 필요한 자산을 대출할 수 있습니다.</p><div className={s.badges}>{['자산 매도 없이 담보 활용','시간 단위 이자 계산','LTV 위험관리','조기 상환 지원'].map(x=><span className={s.badge} key={x}><i className={s.dot}>✓</i>{x}</span>)}</div></div><div className={s.loginBox}>{logged?<><strong>내 대출 현황</strong><p>활성 대출, 현재 LTV, 누적 이자와 상환 상태를 아래에서 확인하세요.</p><Link className={s.primary} style={{display:'inline-flex',alignItems:'center',justifyContent:'center',textDecoration:'none'}} href="#my-loans">내 대출 보기</Link></>:<><strong>보유 자산으로 대출을 신청하려면 로그인하세요.</strong><p>로그인 후 담보 자산과 대출 가능 상품을 확인할 수 있습니다.</p><Link className={s.primary} style={{display:'inline-flex',alignItems:'center',justifyContent:'center',textDecoration:'none'}} href="/login">Log in</Link></>}</div></div></div></section>
  <section className={s.body}><div className={s.shell}><div className={s.steps}>{[['01','상품 선택'],['02','담보·금액 설정'],['03','심사 및 대출 실행'],['04','상환 및 담보 반환']].map(([n,t])=><div className={s.step} key={n}><span className={s.stepNum}>{n}</span><b>{t}</b></div>)}</div>
   <h2 className={s.sectionTitle}>대출 시장</h2><div className={s.market}><div className={s.marketHead}><span>담보 / 대출 자산</span><span>기간</span><span>시간당 / 연 이자율</span><span>초기 / 청산 LTV</span><span>실행</span></div>{products.length?products.map(p=><div className={s.row} key={p.id}><div><div className={s.asset}>{p.collateral_asset} → {p.borrow_asset}</div><span className={s.muted}>{p.name}</span></div><div><b>{p.term_mode==='FIXED'?`${p.term_days}일`:'자유 기간'}</b></div><div><span className={s.rate}>{p.hourly_rate==null?'—':`${(Number(p.hourly_rate)*100).toFixed(6)}%`}</span><span className={s.muted}> / {p.annual_rate==null?'—':pct(p.annual_rate)}</span></div><div><b>{pct(p.initial_ltv)}</b><span className={s.muted}> / {pct(p.liquidation_ltv)}</span></div><button className={s.applyBtn} onClick={()=>openApply(p)}>대출</button></div>):<div style={{padding:28,color:'#838b90'}}>현재 이용 가능한 대출 상품이 없습니다.</div>}</div>
   {logged&&<section id="my-loans" className={s.loans}><h2 className={s.sectionTitle}>내 대출</h2>{loans.length?loans.map(l=>{const outstanding=Math.max(Number(l.principal)-Number(l.repaid_principal||0),0)+Math.max(Number(l.accrued_interest||0)-Number(l.repaid_interest||0),0);return <div className={s.loanCard} key={l.id}><div className={s.loanTop}><div><b>{l.loan_no}</b><span className={s.muted} style={{display:'block'}}>{l.collateral_asset} 담보 · {l.borrow_asset} 대출</span></div><span className={s.status}>{l.status}</span></div><div className={s.loanGrid}><div><small>대출 원금</small><b>{fmt(l.principal,2)} {l.borrow_asset}</b></div><div><small>담보 수량</small><b>{fmt(l.collateral_quantity,8)} {l.collateral_asset}</b></div><div><small>현재 LTV</small><b>{l.current_ltv==null?'—':pct(l.current_ltv)}</b></div><div><small>누적 이자</small><b>{fmt(l.accrued_interest,6)} {l.borrow_asset}</b></div><div><small>현재 상환 예정액</small><b>{fmt(outstanding,6)} {l.borrow_asset}</b></div></div>{['ACTIVE','MARGIN_CALL'].includes(l.status)&&<button className={s.secondary} style={{marginTop:12}} disabled={busy} onClick={()=>requestRepayment(l)}>전액 상환 요청</button>}</div>}):<div className={s.panel} style={{color:'#81898d'}}>대출 내역이 없습니다.</div>}</section>}
   <section className={s.features}><div className={s.feature}><div className={s.featureIcon}>◈</div><h3>다중 담보 자산 구조</h3><p>BTC, ETH 등 지원되는 담보 자산마다 금리와 LTV 기준이 개별 적용됩니다.</p></div><div className={s.feature}><div className={s.featureIcon}>◷</div><h3>시간 단위 이자 계산</h3><p>이자는 원금 × 시간당 이자율 × 경과 시간을 기준으로 계산됩니다. 1시간 미만은 상품 정책에 따라 1시간으로 계산될 수 있습니다.</p></div><div className={s.feature}><div className={s.featureIcon}>⚠</div><h3>LTV 위험 관리</h3><p>담보 가격 변동에 따라 LTV가 변하며 마진콜 또는 청산 기준에 도달할 수 있습니다.</p></div></section>
   <section className={s.faq}><h2 className={s.sectionTitle}>FAQs</h2><details open><summary>암호화폐 담보 대출이란 무엇인가요?</summary><p>보유 암호화폐를 매도하지 않고 담보로 설정해 다른 자산을 대출받는 구조입니다. 신청 후 심사를 통과하면 대출이 실행됩니다.</p></details><details><summary>이자는 어떻게 계산되나요?</summary><p>기본 계산식은 대출 원금 × 시간당 이자율 × 경과 시간입니다. 상품이 고정 기간 상품이면 해당 기간을 기준으로 예상 이자를 표시하고, 누적 이자는 대출 실행 시점부터 계산됩니다.</p></details><details><summary>LTV는 무엇인가요?</summary><p>LTV는 현재 대출 잔액과 누적 이자를 담보 평가금액으로 나눈 비율입니다. 담보 가격이 하락해 LTV가 올라가면 마진콜 또는 청산 검토 상태가 될 수 있습니다.</p></details><details><summary>조기 상환할 수 있나요?</summary><p>가능합니다. 전액 상환이 완료되면 담보 반환 절차가 진행됩니다.</p></details></section>
  </div></section>
  {selected&&<div className={s.modal}><div className={s.modalCard}><div className={s.modalHead}><div><b style={{fontSize:20}}>대출 신청</b><span className={s.muted} style={{display:'block'}}>{selected.collateral_asset} 담보 · {selected.borrow_asset}</span></div><button className={s.close} onClick={()=>setSelected(null)}>×</button></div><div className={s.field}><label>대출 금액 ({selected.borrow_asset})</label><input className={s.input} value={principal} onChange={e=>{setPrincipal(e.target.value);setQuote(null)}} type="number" min={selected.min_borrow}/></div><button className={s.secondary} onClick={calc} disabled={busy}>{busy?'계산 중...':'예상 담보·이자 계산'}</button>{quote&&<><div className={s.quote}><div className={s.quoteBox}><small>예상 필요 담보</small><b>{fmt(quote.required_collateral,8)} {quote.collateral_asset}</b></div><div className={s.quoteBox}><small>예상 이자</small><b>{fmt(quote.estimated_interest,6)} {quote.borrow_asset}</b></div><div className={s.quoteBox}><small>초기 LTV</small><b>{pct(quote.initial_ltv)}</b></div><div className={s.quoteBox}><small>마진콜 / 청산</small><b>{pct(quote.margin_call_ltv)} / {pct(quote.liquidation_ltv)}</b></div></div><div className={s.field} style={{marginTop:14}}><label>담보 수량 ({quote.collateral_asset})</label><input className={s.input} value={collateral} onChange={e=>setCollateral(e.target.value)} type="number" step="any"/></div><div className={s.notice}>신청 시점과 실행 시점의 가격 차이에 따라 필요한 담보 수량이 달라질 수 있습니다.</div><label style={{display:'flex',gap:8,alignItems:'flex-start',fontSize:12,margin:'14px 0'}}><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/><span>대출 이자, LTV 변동, 마진콜 및 담보 청산 가능성을 확인했습니다.</span></label><button className={s.primary} style={{width:'100%'}} onClick={apply} disabled={busy||!agree||!logged}>{logged?(busy?'처리 중...':'대출 신청 제출'):'로그인 후 신청'}</button></>}{msg&&<p className={msg.includes('접수')?s.success:s.error}>{msg}</p>}</div></div>}
 </main>
}