'use client';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';
import s from '@/app/crypto-etf/Index.module.css';
import {useUnifiedWalletDisplay} from '@/lib/useUnifiedWalletDisplay';

type Pos={id:string;product_id:string;status:string;initial_investment:number;total_investment:number;current_value:number;realized_pnl:number;unrealized_pnl:number;roi:number;started_at:string};
type Product={id:string;name:string;risk_level:string;rebalance_frequency:string};
type Holding={position_id:string;asset_symbol:string;target_weight:number;quantity:number;average_cost:number;current_price:number;current_value:number;unrealized_pnl:number};
export default function IndexPortfolioClient(){
 const supabase=useMemo(()=>createBrowserSupabase(),[]);const wallet=useUnifiedWalletDisplay();const [positions,setPositions]=useState<Pos[]>([]),[products,setProducts]=useState<Product[]>([]),[holdings,setHoldings]=useState<Holding[]>([]),[msg,setMsg]=useState('');
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [{data:p},{data:pr},{data:h}]=await Promise.all([supabase.from('index_positions').select('*').order('created_at',{ascending:false}),supabase.from('index_products').select('id,name,risk_level,rebalance_frequency'),supabase.from('index_holdings').select('*')]);setPositions((p||[]) as Pos[]);setProducts((pr||[]) as Product[]);setHoldings((h||[]) as Holding[])}
 useEffect(()=>{load();const id=setInterval(load,10000);return()=>clearInterval(id)},[]);
 const active=positions.filter(x=>!['CLOSED','FAILED'].includes(x.status));const totalInvest=active.reduce((a,b)=>a+Number(b.total_investment),0),value=active.reduce((a,b)=>a+Number(b.current_value),0),pnl=active.reduce((a,b)=>a+Number(b.unrealized_pnl)+Number(b.realized_pnl),0),roi=totalInvest? pnl/totalInvest*100:0;
 async function sell(id:string,pct:number){if(!confirm(`${pct}% 매도하시겠습니까?`))return;const key=crypto.randomUUID();const {error}=await supabase.rpc('sell_index_position',{p_position_id:id,p_percent:pct,p_idempotency_key:key});if(error)setMsg(error.message);else{setMsg('매도가 반영되었습니다.');await load()}}
 return <main className={s.page}><section className={`${s.shell} ${s.hero}`}><span className={s.eyebrow}>MY INDEX</span><h1>내 바스켓 투자</h1><p>실제 구성자산 가격으로 계산된 평가금액과 손익입니다.</p></section>{msg&&<section className={s.shell}><div className={s.warning}>{msg}</div></section>}<section className={s.shell}><div className={s.summary}>{[['총 투자금',totalInvest],['현재 평가금',value],['총 손익',pnl],['총 ROI',`${roi.toFixed(2)}%`],['보유 상품',active.length]].map(([k,v])=><div key={String(k)}><span>{k}</span><b className={typeof v==='number'&&v<0?s.down:''}>{typeof v==='number'?wallet.withUnit(v):v}</b></div>)}</div><div className={s.grid}>{active.map(p=>{const prod=products.find(x=>x.id===p.product_id);const hs=holdings.filter(h=>h.position_id===p.id);return <article className={s.positionCard} key={p.id}><div className={s.positionHead}><div><h3>{prod?.name||'BITMATE INDEX'}</h3><span className={s.muted}>{prod?.risk_level} · {p.status}</span></div><b className={Number(p.unrealized_pnl)>=0?s.up:s.down}>{Number(p.roi).toFixed(2)}%</b></div><div className={s.positionStats}><div><span>누적 투자금</span><b>{wallet.withUnit(Number(p.total_investment))}</b></div><div><span>현재 평가금</span><b>{wallet.withUnit(Number(p.current_value))}</b></div><div><span>평가손익</span><b className={Number(p.unrealized_pnl)>=0?s.up:s.down}>{wallet.withUnit(Number(p.unrealized_pnl))}</b></div><div><span>리밸런싱</span><b>{prod?.rebalance_frequency||'—'}</b></div></div><div>{hs.map(h=><div className={s.allocationRow} key={h.asset_symbol}><b>{h.asset_symbol}</b><div><div className={s.bar}><i style={{width:`${Math.min(100,Math.max(0,Number(h.target_weight)*100))}%`}}/></div><small className={s.muted}>{Number(h.quantity).toFixed(6)} · {wallet.withUnit(Number(h.current_value))}</small></div><span>{(Number(h.target_weight)*100).toFixed(0)}%</span></div>)}</div><div className={s.cardFoot}><small>시작 {new Date(p.started_at).toLocaleDateString()}</small><div><button className={s.ghost} onClick={()=>sell(p.id,25)}>25%</button> <button className={s.ghost} onClick={()=>sell(p.id,50)}>50%</button> <button className={s.btn} onClick={()=>sell(p.id,100)}>전체매도</button></div></div></article>})}</div>{!active.length&&<div className={s.empty}>보유 중인 BITMATE INDEX가 없습니다.</div>}</section></main>;
}
