'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {createBrowserSupabase} from '@/lib/supabase-browser';
import {useUnifiedWalletDisplay} from '@/lib/useUnifiedWalletDisplay';

type Row={id:string;settlement_date:string;principal:number;applied_rate:number;base_reward:number;boost_rate:number;boost_reward:number;final_reward:number;status:string;settled_at:string;position_id:string};
type State={principal:number;mining_power:number;active_positions:number;today_reward:number;total_reward:number;level:number;level_name:string;mining_days:number};
const money=(v:number)=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:8});
export default function MyMiningClient(){
  const supabase=useMemo(()=>createBrowserSupabase(),[]); const wallet=useUnifiedWalletDisplay(); const [state,setState]=useState<State|null>(null); const [rows,setRows]=useState<Row[]>([]); const [login,setLogin]=useState(true);
  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){setLogin(false);return;} const {data:g}=await supabase.rpc('get_my_mining_game_state'); setState(g as State); const {data:r}=await supabase.from('mining_daily_settlements').select('id,settlement_date,principal,applied_rate,base_reward,boost_rate,boost_reward,final_reward,status,settled_at,position_id').order('settlement_date',{ascending:false}).limit(100); setRows((r||[]) as Row[]);})();},[supabase]);
  if(!login)return <main className="tradePage"><section className="tradeHero"><div className="xtShell"><h1>My Mining</h1><p>내 채굴 현황을 보려면 로그인해주세요.</p><Link href="/login" className="limeBtn">Log in</Link></div></section></main>;
  return <main className="tradePage"><section className="tradeHero"><div className="xtShell"><span className="sectionLabel">MY MINING</span><h1>내 채굴</h1><p>Position은 각각 별도로 관리하고, 메인 화면에서는 합산 현황을 보여줍니다.</p></div></section><section className="xtShell miningQuickStats"><div><span>총 채굴 자산</span><b>{wallet.withUnit(state?.principal||0)}</b></div><div><span>총 Mining Power</span><b>{money(state?.mining_power||0)} TH/s</b></div><div><span>오늘 채굴 보상</span><b>{wallet.withUnit(state?.today_reward||0)}</b></div><div><span>누적 채굴 보상</span><b>{wallet.withUnit(state?.total_reward||0)}</b></div></section><section className="xtShell miningHistory"><div className="sectionTitle"><span>MINING HISTORY</span><h2>정산 내역</h2></div><div className="historyTable"><div className="historyRow head"><span>날짜</span><span>기준금액</span><span>적용률</span><span>기본 보상</span><span>BOOST</span><span>최종 보상</span><span>상태</span></div>{rows.length?rows.map(r=><div className="historyRow" key={r.id}><span>{r.settlement_date}</span><span>{money(r.principal)}</span><span>{(Number(r.applied_rate)*100).toFixed(2)}%</span><span>{money(r.base_reward)}</span><span>{money(r.boost_reward)}</span><span>{wallet.withUnit(r.final_reward)}</span><span className={r.status==='PAID'?'paid':'failed'}>{r.status}</span></div>):<div className="emptyMining"><h3>아직 정산 내역이 없습니다.</h3><p>채굴 보상이 확정되면 여기에 표시됩니다.</p><Link href="/mining" className="limeBtn">채굴 시작</Link></div>}</div></section></main>;
}
