import Link from 'next/link';

const boosts=[
 {name:'Starter Boost',power:'+10%',term:'24시간',source:'Reward Hub / Event',state:'사용 가능'},
 {name:'Power Boost',power:'+25%',term:'3일',source:'거래량 / Referral',state:'조건 달성'},
 {name:'Pro Boost',power:'+50%',term:'7일',source:'BTMT / Campaign',state:'운영 정책'},
 {name:'Max Boost',power:'+100%',term:'24시간',source:'Special Event',state:'이벤트 전용'},
];
export default function MiningBoostPage(){return <main style={{minHeight:'calc(100vh - 72px)',background:'#08090a',color:'#f4f6f7',padding:'44px 0 90px'}}><div className="xtShell">
 <section style={{display:'grid',gridTemplateColumns:'1.05fr .95fr',gap:26,alignItems:'stretch'}}>
  <div style={{padding:'24px 0 34px'}}><span style={{color:'#b9ff31',fontSize:11,fontWeight:900,letterSpacing:'.14em'}}>MINING POWER BOOST</span><h1 style={{fontSize:'clamp(42px,6vw,70px)',lineHeight:1.02,letterSpacing:'-.055em',margin:'12px 0 18px'}}>Boost your<br/>Mining Power.</h1><p style={{maxWidth:700,color:'#90989d',fontSize:16,lineHeight:1.75}}>Mining Boost는 기본 Mining Power에 일정 비율을 추가 적용하는 보조 프로그램입니다. 실제 적용률, 사용기간, 획득조건은 운영 정책과 서버 상태를 기준으로 반영됩니다.</p><div style={{display:'flex',gap:10,marginTop:24,flexWrap:'wrap'}}><Link href="/mining" style={{height:44,padding:'0 18px',borderRadius:8,background:'#b9ff31',color:'#0d1207',fontWeight:900,display:'inline-flex',alignItems:'center'}}>Mining Home</Link><Link href="/my-mining" style={{height:44,padding:'0 18px',borderRadius:8,border:'1px solid #34393d',fontWeight:800,display:'inline-flex',alignItems:'center'}}>My Mining</Link></div></div>
  <div style={{border:'1px solid #2a2e31',borderRadius:18,background:'radial-gradient(circle at 70% 30%,rgba(185,255,49,.13),transparent 42%),#111315',padding:24,display:'grid',alignContent:'center',gap:14}}><small style={{color:'#778086',fontWeight:900,letterSpacing:'.12em'}}>CURRENT STATUS</small>{[['기본 Mining Power','서버 계산'],['적용 중 Boost','없음'],['오늘 예상 추가 보상','—'],['다음 만료 예정','—']].map(([k,v])=><div key={k} style={{display:'flex',justifyContent:'space-between',gap:16,padding:'13px 0',borderBottom:'1px solid #23272a'}}><span style={{color:'#7f888d',fontSize:13}}>{k}</span><b>{v}</b></div>)}</div>
 </section>
 <section style={{marginTop:30}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginBottom:18}}><div><small style={{color:'#757e83',fontWeight:900,letterSpacing:'.12em'}}>BOOST CATALOG</small><h2 style={{fontSize:30,margin:'7px 0 0'}}>Boost 프로그램</h2></div><span style={{fontSize:12,color:'#6f787d'}}>정책 활성화 시 실제 적용 가능</span></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:14}}>{boosts.map(b=><article key={b.name} style={{minHeight:210,border:'1px solid #25292c',background:'#111315',borderRadius:14,padding:20,display:'flex',flexDirection:'column'}}><small style={{color:'#788086',fontWeight:900}}>{b.state}</small><h3 style={{fontSize:20,margin:'9px 0 0'}}>{b.name}</h3><strong style={{fontSize:36,color:'#b9ff31',marginTop:16}}>{b.power}</strong><div style={{display:'grid',gap:8,marginTop:'auto',paddingTop:18,borderTop:'1px solid #222629'}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12}}><span style={{color:'#747d82'}}>기간</span><b>{b.term}</b></div><div style={{display:'flex',justifyContent:'space-between',fontSize:12}}><span style={{color:'#747d82'}}>획득</span><b>{b.source}</b></div></div></article>)}</div>
 </section>
 <section style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:34}}><div style={{border:'1px solid #25292c',borderRadius:14,background:'#0e1011',padding:22}}><h2 style={{fontSize:22,margin:'0 0 14px'}}>Boost 획득 방법</h2>{[['Reward Hub','미션 보상으로 Boost 지급'],['Referral','추천 실적 조건 달성'],['Trading Volume','기간 누적 거래량 조건'],['BTMT Membership','등급별 Boost 혜택'],['Campaign','기간 한정 이벤트 지급']].map(([a,b])=><div key={a} style={{display:'grid',gridTemplateColumns:'150px 1fr',gap:14,padding:'12px 0',borderBottom:'1px solid #1f2325'}}><b style={{fontSize:13}}>{a}</b><span style={{fontSize:13,color:'#7f888d'}}>{b}</span></div>)}</div><div style={{border:'1px solid #25292c',borderRadius:14,background:'#0e1011',padding:22}}><h2 style={{fontSize:22,margin:'0 0 14px'}}>적용 원칙</h2><p style={{color:'#81898e',fontSize:13,lineHeight:1.75}}>Boost는 기본 Mining Power 또는 운영정책상 지정된 채굴 효율에 추가 적용됩니다. 중복 적용, 최대 배율, 만료시간, 특정 상품 제외 여부는 서버 정책이 최종 결정합니다.</p><div style={{display:'grid',gap:9,marginTop:16}}>{['적용 전/후 예상 보상 비교','Boost 시작·만료 시간 기록','획득 및 사용 이력 보관','실제 추가 채굴량 별도 표시'].map(x=><div key={x} style={{padding:'11px 12px',background:'#171a1c',border:'1px solid #24282b',borderRadius:9,fontSize:13}}>✓ {x}</div>)}</div></div></section>
 <section style={{marginTop:34,border:'1px solid #25292c',borderRadius:14,background:'#111315',padding:22}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap'}}><div><b style={{fontSize:18}}>Boost History</b><p style={{color:'#7f888d',fontSize:13,margin:'7px 0 0'}}>획득, 적용, 만료, 추가 보상 기록을 계정 기준으로 표시할 수 있도록 구성합니다.</p></div><Link href="/more/reward-hub" style={{color:'#b9ff31',fontSize:13,fontWeight:900}}>Reward Hub ›</Link></div></section>
 </div></main>}
