'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';

type Boost={id:string;name:string;starts_at:string;ends_at:string;bonus_rate:number;active:boolean;condition:any};
type UserBoost={id:string;active:boolean;awarded_at:string;expires_at:string|null;boost_event_id:string};
type Position={id:string;mining_power:number;principal:number;status:string};
export default function MiningBoostPage(){const supabase=useMemo(()=>createBrowserSupabase(),[]);const [boosts,setBoosts]=useState<Boost[]>([]);const [mine,setMine]=useState<UserBoost[]>([]);const [positions,setPositions]=useState<Position[]>([]);const [logged,setLogged]=useState(false);const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const now=new Date().toISOString();const [{data:b},{data:{user}}]=await Promise.all([supabase.from('mining_boost_events').select('id,name,starts_at,ends_at,bonus_rate,active,condition').eq('active',true).gte('ends_at',now).order('bonus_rate',{ascending:true}),supabase.auth.getUser()]);setBoosts((b||[]) as Boost[]);setLogged(!!user);if(user){const [{data:u},{data:p}]=await Promise.all([supabase.from('mining_user_boosts').select('id,active,awarded_at,expires_at,boost_event_id').eq('user_id',user.id).order('awarded_at',{ascending:false}),supabase.from('mining_positions').select('id,mining_power,principal,status').eq('user_id',user.id).in('status',['MINING','PAUSED'])]);setMine((u||[]) as UserBoost[]);setPositions((p||[]) as Position[])}setLoading(false)})()},[supabase]);
 const activeMine=mine.filter(x=>x.active&&(!x.expires_at||new Date(x.expires_at)>new Date()));const totalPower=positions.reduce((s,p)=>s+Number(p.mining_power||0),0);const boostRate=activeMine.reduce((s,u)=>{const b=boosts.find(x=>x.id===u.boost_event_id);return s+Number(b?.bonus_rate||0)},0);
 return <main style={{minHeight:'calc(100vh - 72px)',background:'#08090a',color:'#f4f6f7',padding:'44px 0 90px'}}><div className="xtShell">
  <section style={{display:'grid',gridTemplateColumns:'1.05fr .95fr',gap:26,alignItems:'stretch'}}><div style={{padding:'24px 0 34px'}}><span style={{color:'#b9ff31',fontSize:11,fontWeight:900,letterSpacing:'.14em'}}>MINING POWER BOOST</span><h1 style={{fontSize:'clamp(42px,6vw,70px)',lineHeight:1.02,letterSpacing:'-.055em',margin:'12px 0 18px'}}>Boost your<br/>Mining Power.</h1><p style={{maxWidth:700,color:'#90989d',fontSize:16,lineHeight:1.75}}>현재 활성화된 Boost 정책과 내 계정에 지급된 Boost를 실제 서버 데이터 기준으로 확인합니다.</p><div style={{display:'flex',gap:10,marginTop:24,flexWrap:'wrap'}}><Link href="/mining" style={{height:44,padding:'0 18px',borderRadius:8,background:'#b9ff31',color:'#0d1207',fontWeight:900,display:'inline-flex',alignItems:'center'}}>Mining Home</Link><Link href="/my-mining" style={{height:44,padding:'0 18px',borderRadius:8,border:'1px solid #34393d',fontWeight:800,display:'inline-flex',alignItems:'center'}}>My Mining</Link></div></div><div style={{border:'1px solid #2a2e31',borderRadius:18,background:'radial-gradient(circle at 70% 30%,rgba(185,255,49,.13),transparent 42%),#111315',padding:24,display:'grid',alignContent:'center',gap:14}}><small style={{color:'#778086',fontWeight:900,letterSpacing:'.12em'}}>CURRENT STATUS</small>{[['기본 Mining Power',logged?totalPower.toLocaleString():'로그인 필요'],['적용 중 Boost',logged?`${activeMine.length}개`:'—'],['추가 Boost Rate',logged?`${(boostRate*100).toFixed(2)}%`:'—'],['활성 Position',logged?`${positions.length}개`:'—']].map(([k,v])=><div key={k} style={{display:'flex',justifyContent:'space-between',gap:16,padding:'13px 0',borderBottom:'1px solid #23272a'}}><span style={{color:'#7f888d',fontSize:13}}>{k}</span><b>{String(v)}</b></div>)}</div></section>
  <section style={{marginTop:30}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginBottom:18}}><div><small style={{color:'#757e83',fontWeight:900,letterSpacing:'.12em'}}>LIVE BOOST CATALOG</small><h2 style={{fontSize:30,margin:'7px 0 0'}}>현재 활성 Boost</h2></div><span style={{fontSize:12,color:'#6f787d'}}>{loading?'—':`${boosts.length} active`}</span></div>{boosts.length?<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:14}}>{boosts.map(b=><article key={b.id} style={{minHeight:210,border:'1px solid #25292c',background:'#111315',borderRadius:14,padding:20,display:'flex',flexDirection:'column'}}><small style={{color:'#788086',fontWeight:900}}>ACTIVE</small><h3 style={{fontSize:20,margin:'9px 0 0'}}>{b.name}</h3><strong style={{fontSize:36,color:'#b9ff31',marginTop:16}}>+{(Number(b.bonus_rate)*100).toFixed(2)}%</strong><div style={{display:'grid',gap:8,marginTop:'auto',paddingTop:18,borderTop:'1px solid #222629'}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12}}><span style={{color:'#747d82'}}>시작</span><b>{new Date(b.starts_at).toLocaleDateString('ko-KR')}</b></div><div style={{display:'flex',justifyContent:'space-between',fontSize:12}}><span style={{color:'#747d82'}}>만료</span><b>{new Date(b.ends_at).toLocaleDateString('ko-KR')}</b></div></div></article>)}</div>:<div style={{padding:28,border:'1px solid #25292c',borderRadius:14,color:'#7f888d'}}>현재 활성화된 Boost 이벤트가 없습니다.</div>}</section>
  <section style={{marginTop:34,border:'1px solid #25292c',borderRadius:14,background:'#111315',padding:22}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap'}}><div><b style={{fontSize:18}}>My Boost History</b><p style={{color:'#7f888d',fontSize:13,margin:'7px 0 0'}}>획득/적용/만료 기록은 계정별 mining_user_boosts에서 불러옵니다.</p></div>{!logged&&<Link href="/login" style={{color:'#b9ff31',fontWeight:900}}>Log in ›</Link>}</div><div style={{marginTop:14}}>{logged?(mine.length?mine.map(u=>{const b=boosts.find(x=>x.id===u.boost_event_id);return <div key={u.id} style={{display:'grid',gridTemplateColumns:'1fr 140px 100px',gap:12,padding:'12px 0',borderBottom:'1px solid #1f2325',fontSize:13}}><span><b>{b?.name||'Boost Event'}</b><small style={{display:'block',color:'#71797e',marginTop:4}}>{new Date(u.awarded_at).toLocaleString('ko-KR')}</small></span><span>{u.expires_at?new Date(u.expires_at).toLocaleDateString('ko-KR'):'No expiry'}</span><b style={{textAlign:'right',color:u.active?'#b9ff31':'#7e878c'}}>{u.active?'ACTIVE':'ENDED'}</b></div>}):<p style={{color:'#7f888d'}}>아직 Boost 지급 내역이 없습니다.</p>):<p style={{color:'#7f888d'}}>로그인 후 내 Boost 이력을 확인할 수 있습니다.</p>}</div></section>
 </div></main>}
