'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';

type Course={id:string;slug:string;category:string;title:string;description:string;level:string;estimated_minutes:number;sort_order:number};
type Lesson={id:string;course_id:string;slug:string;title:string;lesson_order:number};
const koLevel=(x:string)=>x==='ADVANCED'?'고급':x==='INTERMEDIATE'?'중급':'초급';
export default function AcademyPage(){
 const supabase=useMemo(()=>createBrowserSupabase(),[]);const [courses,setCourses]=useState<Course[]>([]);const [loading,setLoading]=useState(true);const [continueItem,setContinueItem]=useState<{course:Course;lesson:Lesson;done:number;total:number}|null>(null);
 useEffect(()=>{(async()=>{const {data:cs}=await supabase.from('academy_courses').select('id,slug,category,title,description,level,estimated_minutes,sort_order').eq('published',true).order('sort_order');const list=(cs||[]) as Course[];setCourses(list);const {data:{user}}=await supabase.auth.getUser();if(user&&list.length){const ids=list.map(c=>c.id);const {data:ls}=await supabase.from('academy_lessons').select('id,course_id,slug,title,lesson_order').in('course_id',ids).eq('published',true).order('lesson_order');const lessons=(ls||[]) as Lesson[];const {data:pr}=await supabase.from('academy_progress').select('lesson_id,completed_at').eq('user_id',user.id).order('completed_at',{ascending:false});const doneSet=new Set((pr||[]).map(x=>x.lesson_id));for(const c of list){const cl=lessons.filter(x=>x.course_id===c.id).sort((a,b)=>a.lesson_order-b.lesson_order);if(!cl.length)continue;const next=cl.find(x=>!doneSet.has(x.id));if(next){setContinueItem({course:c,lesson:next,done:cl.filter(x=>doneSet.has(x.id)).length,total:cl.length});break;}}}setLoading(false)})()},[supabase]);
 return <main style={{minHeight:'calc(100vh - 72px)',background:'#08090a',color:'#f4f6f7',padding:'44px 0 90px'}}><div className="xtShell">
 <section style={{display:'grid',gridTemplateColumns:'1.05fr .95fr',gap:28,alignItems:'center',padding:'28px 0 44px'}}><div><span style={{fontSize:11,color:'#b9ff31',fontWeight:900,letterSpacing:'.14em'}}>BITMATE ACADEMY</span><h1 style={{fontSize:'clamp(42px,6vw,72px)',letterSpacing:'-.055em',lineHeight:1.02,margin:'12px 0 18px'}}>Learn before<br/>you trade.</h1><p style={{maxWidth:720,color:'#90989d',fontSize:16,lineHeight:1.75}}>거래 구조, 상품별 위험, 보안과 실제 사용법을 단계별 코스로 학습합니다. 학습 완료 기록은 로그인 계정 기준으로 저장됩니다.</p><div style={{display:'flex',gap:10,marginTop:24,flexWrap:'wrap'}}><a href="#tracks" style={{height:44,padding:'0 18px',borderRadius:8,background:'#b9ff31',color:'#0e1209',fontWeight:900,display:'inline-flex',alignItems:'center'}}>학습 시작</a><Link href="/more/academy/glossary" style={{height:44,padding:'0 18px',borderRadius:8,border:'1px solid #34393d',display:'inline-flex',alignItems:'center',fontWeight:800}}>거래 용어사전</Link></div></div><div style={{border:'1px solid #2b3033',borderRadius:18,background:'linear-gradient(145deg,#171a1c,#0d0f10)',padding:24,minHeight:260,display:'grid',alignContent:'center',gap:12}}>{[['01','계정·보안'],['02','입출금'],['03','거래 기본'],['04','상품별 리스크'],['05','실전 기능']].map(([n,t])=><div key={n} style={{display:'grid',gridTemplateColumns:'44px 1fr',alignItems:'center',padding:'11px 12px',border:'1px solid #24282b',background:'#121416',borderRadius:10}}><b style={{color:'#b9ff31',fontSize:12}}>{n}</b><span style={{fontWeight:800}}>{t}</span></div>)}</div></section>
 {continueItem&&<section style={{margin:'0 0 34px',border:'1px solid #355718',background:'linear-gradient(120deg,#11190d,#0d1110)',borderRadius:14,padding:22,display:'flex',justifyContent:'space-between',alignItems:'center',gap:20,flexWrap:'wrap'}}><div><small style={{color:'#b9ff31',fontWeight:900,letterSpacing:'.12em'}}>CONTINUE LEARNING</small><h2 style={{fontSize:24,margin:'8px 0 5px'}}>{continueItem.course.title}</h2><p style={{margin:0,color:'#8d969a',fontSize:13}}>다음 강의: {continueItem.lesson.title} · {continueItem.done}/{continueItem.total} 완료</p></div><Link href={`/more/academy/${continueItem.course.slug}#${continueItem.lesson.slug}`} style={{height:44,padding:'0 20px',borderRadius:8,background:'#b9ff31',color:'#0c1108',fontWeight:900,display:'inline-flex',alignItems:'center'}}>이어서 학습하기 ›</Link></section>}
 <section id="tracks"><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginBottom:18}}><div><small style={{color:'#737c81',fontWeight:900,letterSpacing:'.12em'}}>LEARNING TRACKS</small><h2 style={{fontSize:30,margin:'7px 0 0'}}>학습 코스</h2></div><span style={{color:'#737c81',fontSize:12}}>{loading?'—':`${courses.length} courses`}</span></div>{loading?<div style={{color:'#747c81'}}>불러오는 중...</div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:14}}>{courses.map(c=><Link key={c.id} href={`/more/academy/${c.slug}`} style={{minHeight:190,border:'1px solid #25292c',background:'#111315',borderRadius:14,padding:20,display:'flex',flexDirection:'column',color:'#f4f6f7'}}><small style={{color:'#b9ff31',fontSize:10,fontWeight:900,letterSpacing:'.1em'}}>{koLevel(c.level)} · {c.category}</small><h3 style={{fontSize:20,margin:'10px 0 8px'}}>{c.title}</h3><p style={{fontSize:13,color:'#81898e',lineHeight:1.65,margin:0,flex:1}}>{c.description}</p><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',paddingTop:16,borderTop:'1px solid #222629',marginTop:16}}><span style={{fontSize:12,color:'#70787d'}}>{c.estimated_minutes} min</span><b style={{fontSize:12}}>Start ›</b></div></Link>)}</div>}</section>
 <section style={{marginTop:42,display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}><Link href="/more/academy/glossary" style={{border:'1px solid #25292c',background:'#111315',borderRadius:14,padding:22,color:'#f4f6f7'}}><small style={{color:'#b9ff31',fontWeight:900}}>GLOSSARY</small><h3 style={{fontSize:21,margin:'10px 0'}}>거래 용어사전</h3><p style={{color:'#7f888d',fontSize:13,lineHeight:1.7}}>Mark Price, Funding, ROE, LTV, Maker/Taker 등 BITMATE 화면에서 쓰는 핵심 용어를 검색하고 상품별로 확인합니다.</p><b style={{fontSize:12}}>용어사전 열기 ›</b></Link><div style={{border:'1px solid #25292c',background:'#111315',borderRadius:14,padding:22}}><small style={{color:'#b9ff31',fontWeight:900}}>PROGRESS</small><h3 style={{fontSize:21,margin:'10px 0'}}>학습 기록</h3><p style={{color:'#7f888d',fontSize:13,lineHeight:1.7}}>완료한 강의는 계정별로 저장되고, 다음 방문 시 마지막 진행상태를 기준으로 이어서 학습할 수 있습니다.</p></div></section>
 </div></main>}
