'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';

type Course={id:string;slug:string;category:string;title:string;description:string;level:string;estimated_minutes:number;sort_order:number};
const koLevel=(x:string)=>x==='ADVANCED'?'고급':x==='INTERMEDIATE'?'중급':'초급';
export default function AcademyPage(){const supabase=useMemo(()=>createBrowserSupabase(),[]);const [courses,setCourses]=useState<Course[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{supabase.from('academy_courses').select('id,slug,category,title,description,level,estimated_minutes,sort_order').eq('published',true).order('sort_order').then(({data})=>{setCourses((data||[]) as Course[]);setLoading(false)})},[supabase]);return <main style={{minHeight:'calc(100vh - 72px)',background:'#08090a',color:'#f4f6f7',padding:'44px 0 90px'}}><div className="xtShell">
<section style={{display:'grid',gridTemplateColumns:'1.05fr .95fr',gap:28,alignItems:'center',padding:'28px 0 44px'}}><div><span style={{fontSize:11,color:'#b9ff31',fontWeight:900,letterSpacing:'.14em'}}>BITMATE ACADEMY</span><h1 style={{fontSize:'clamp(42px,6vw,72px)',letterSpacing:'-.055em',lineHeight:1.02,margin:'12px 0 18px'}}>Learn before<br/>you trade.</h1><p style={{maxWidth:720,color:'#90989d',fontSize:16,lineHeight:1.75}}>거래 구조, 상품별 위험, 보안과 실제 사용법을 단계별 코스로 학습합니다. 학습 완료 기록은 로그인 계정 기준으로 저장됩니다.</p><div style={{display:'flex',gap:10,marginTop:24,flexWrap:'wrap'}}><a href="#tracks" style={{height:44,padding:'0 18px',borderRadius:8,background:'#b9ff31',color:'#0e1209',fontWeight:900,display:'inline-flex',alignItems:'center'}}>학습 시작</a><Link href="/more/notice" style={{height:44,padding:'0 18px',borderRadius:8,border:'1px solid #34393d',display:'inline-flex',alignItems:'center',fontWeight:800}}>공지센터</Link></div></div><div style={{border:'1px solid #2b3033',borderRadius:18,background:'linear-gradient(145deg,#171a1c,#0d0f10)',padding:24,minHeight:260,display:'grid',alignContent:'center',gap:12}}>{[['01','계정·보안'],['02','입출금'],['03','거래 기본'],['04','상품별 리스크'],['05','실전 기능']].map(([n,t])=><div key={n} style={{display:'grid',gridTemplateColumns:'44px 1fr',alignItems:'center',padding:'11px 12px',border:'1px solid #24282b',background:'#121416',borderRadius:10}}><b style={{color:'#b9ff31',fontSize:12}}>{n}</b><span style={{fontWeight:800}}>{t}</span></div>)}</div></section>
<section id="tracks"><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginBottom:18}}><div><small style={{color:'#737c81',fontWeight:900,letterSpacing:'.12em'}}>LEARNING TRACKS</small><h2 style={{fontSize:30,margin:'7px 0 0'}}>학습 코스</h2></div><span style={{color:'#737c81',fontSize:12}}>{loading?'—':`${courses.length} courses`}</span></div>{loading?<div style={{color:'#747c81'}}>불러오는 중...</div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:14}}>{courses.map(c=><Link key={c.id} href={`/more/academy/${c.slug}`} style={{minHeight:190,border:'1px solid #25292c',background:'#111315',borderRadius:14,padding:20,display:'flex',flexDirection:'column',color:'#f4f6f7'}}><small style={{color:'#b9ff31',fontSize:10,fontWeight:900,letterSpacing:'.1em'}}>{koLevel(c.level)} · {c.category}</small><h3 style={{fontSize:20,margin:'10px 0 8px'}}>{c.title}</h3><p style={{fontSize:13,color:'#81898e',lineHeight:1.65,margin:0,flex:1}}>{c.description}</p><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',paddingTop:16,borderTop:'1px solid #222629',marginTop:16}}><span style={{fontSize:12,color:'#70787d'}}>{c.estimated_minutes} min</span><b style={{fontSize:12}}>Start ›</b></div></Link>)}</div>}</section>
<section style={{marginTop:42,display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}><div style={{border:'1px solid #25292c',background:'#111315',borderRadius:14,padding:22}}><small style={{color:'#b9ff31',fontWeight:900}}>GLOSSARY</small><h3 style={{fontSize:21,margin:'10px 0'}}>거래 용어사전</h3><p style={{color:'#7f888d',fontSize:13,lineHeight:1.7}}>Mark Price, Funding, ROE, LTV, Maker/Taker 등 실제 BITMATE 화면에서 쓰는 용어를 코스별로 학습합니다.</p></div><div style={{border:'1px solid #25292c',background:'#111315',borderRadius:14,padding:22}}><small style={{color:'#b9ff31',fontWeight:900}}>PROGRESS</small><h3 style={{fontSize:21,margin:'10px 0'}}>학습 기록</h3><p style={{color:'#7f888d',fontSize:13,lineHeight:1.7}}>로그인 후 완료 버튼을 누른 강의는 계정별 Academy Progress에 저장됩니다.</p></div></section>
</div></main>}
