'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';

type RefRow={id:string;referred_user_id:string;status:string;joined_at:string;qualified_at:string|null};
type Reward={id:string;reward_type:string;amount:number;asset:string;status:string;created_at:string;paid_at:string|null};
const faq=[['레퍼럴 프로그램은 어떻게 이용하나요?','로그인 후 개인 추천 링크와 추천 코드를 발급받아 공유할 수 있습니다.'],['추천 상태는 언제 바뀌나요?','가입 후 운영 정책의 인정 조건을 충족하면 PENDING에서 QUALIFIED로 변경될 수 있습니다.'],['리워드는 언제 표시되나요?','서버에서 생성된 referral_reward_events 중 본인 계정에 해당하는 기록만 표시됩니다.'],['Reward Hub는 누구나 이용할 수 있나요?','파트너 관리 기능은 승인된 Referral Partner 계정만 사용할 수 있습니다.']];
export default function ReferralPage(){const supabase=useMemo(()=>createBrowserSupabase(),[]);const [logged,setLogged]=useState(false);const [code,setCode]=useState('');const [refs,setRefs]=useState<RefRow[]>([]);const [rewards,setRewards]=useState<Reward[]>([]);const [loading,setLoading]=useState(true);const [copied,setCopied]=useState(false);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return;}setLogged(true);const [{data:c},{data:r},{data:w}]=await Promise.all([supabase.rpc('get_or_create_referral_code'),supabase.from('referrals').select('id,referred_user_id,status,joined_at,qualified_at').eq('referrer_user_id',user.id).order('joined_at',{ascending:false}),supabase.from('referral_reward_events').select('id,reward_type,amount,asset,status,created_at,paid_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(50)]);setCode((c as string)||'');setRefs((r||[]) as RefRow[]);setRewards((w||[]) as Reward[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const qualified=refs.filter(x=>x.status==='QUALIFIED').length;const paid=rewards.filter(x=>x.status==='PAID').reduce((s,x)=>s+Number(x.amount||0),0);const pending=rewards.filter(x=>['PENDING','APPROVED'].includes(x.status)).reduce((s,x)=>s+Number(x.amount||0),0);const invite=typeof window!=='undefined'&&code?`${window.location.origin}/signup?ref=${encodeURIComponent(code)}`:'';
 async function copy(){if(!invite)return;await navigator.clipboard.writeText(invite);setCopied(true);setTimeout(()=>setCopied(false),1200)}
 return <main style={{minHeight:'calc(100vh - 72px)',background:'#050607',color:'#f5f7f8'}}><div className="xtShell" style={{paddingTop:28,paddingBottom:90}}>
  <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.05fr) minmax(320px,.95fr)',gap:32,alignItems:'stretch'}}><div style={{padding:'24px 0'}}><span style={{color:'#b9ff31',fontSize:12,fontWeight:800,letterSpacing:'.12em'}}>BITMATE REFERRAL PROGRAM</span><h1 style={{fontSize:'clamp(44px,5.4vw,72px)',lineHeight:1.02,letterSpacing:'-.055em',margin:'14px 0 20px'}}>Invite. Track.<br/>Reward.</h1><p style={{maxWidth:680,color:'#9aa2a7',fontSize:16,lineHeight:1.75}}>추천 링크 발급부터 추천 상태, 확정 리워드까지 실제 계정 데이터로 확인합니다.</p>{logged?<div style={{display:'grid',gap:10,marginTop:26,maxWidth:620}}><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:8}}><div style={{height:46,padding:'0 14px',border:'1px solid #31363a',borderRadius:9,background:'#101214',display:'flex',alignItems:'center',overflow:'hidden'}}><span style={{whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',fontSize:13}}>{invite||'링크 생성 중...'}</span></div><button onClick={copy} style={{padding:'0 18px',border:0,borderRadius:9,background:'#b9ff31',fontWeight:900}}>{copied?'Copied':'Copy'}</button></div><small style={{color:'#70787d'}}>Referral Code · <b style={{color:'#fff'}}>{code||'—'}</b></small></div>:<Link href="/login" style={{marginTop:28,minHeight:46,padding:'0 20px',borderRadius:8,background:'#b9ff31',color:'#0d1207',fontWeight:900,display:'inline-flex',alignItems:'center'}}>Log in to get referral link</Link>}</div><div style={{border:'1px solid #2a2e31',background:'#111315',borderRadius:18,padding:24}}><small style={{color:'#737c81',fontWeight:900,letterSpacing:'.12em'}}>MY REFERRAL SUMMARY</small><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:16}}>{[['총 초대',loading?'—':refs.length],['Qualified',loading?'—':qualified],['지급 완료',loading?'—':`${paid.toLocaleString()} USDT`],['지급 대기',loading?'—':`${pending.toLocaleString()} USDT`]].map(([k,v])=><div key={k} style={{padding:'16px 14px',borderRadius:10,background:'#191c1e',border:'1px solid #24282b'}}><small style={{display:'block',color:'#747c81',marginBottom:6}}>{k}</small><b style={{fontSize:20}}>{String(v)}</b></div>)}</div></div></section>
  <section style={{display:'grid',gridTemplateColumns:'1.15fr .85fr',gap:16,marginTop:28}}><div style={{border:'1px solid #25292c',borderRadius:12,background:'#0d0f10',padding:22}}><h2 style={{fontSize:22,margin:'0 0 16px'}}>Referral History</h2>{!logged?<p style={{color:'#737c81'}}>로그인 후 추천 내역을 확인할 수 있습니다.</p>:refs.length?refs.map(r=><div key={r.id} style={{display:'grid',gridTemplateColumns:'1fr 120px 120px',gap:10,padding:'13px 0',borderBottom:'1px solid #1f2325',fontSize:13}}><span>{r.referred_user_id.slice(0,8)}••••</span><span>{new Date(r.joined_at).toLocaleDateString('ko-KR')}</span><b style={{textAlign:'right',color:r.status==='QUALIFIED'?'#b9ff31':'#c5c9cb'}}>{r.status}</b></div>):<p style={{color:'#737c81'}}>아직 추천 회원이 없습니다.</p>}</div><div style={{border:'1px solid #25292c',borderRadius:12,background:'#0d0f10',padding:22}}><h2 style={{fontSize:22,margin:'0 0 16px'}}>Reward History</h2>{!logged?<p style={{color:'#737c81'}}>로그인이 필요합니다.</p>:rewards.length?rewards.map(r=><div key={r.id} style={{display:'grid',gridTemplateColumns:'1fr auto',gap:10,padding:'13px 0',borderBottom:'1px solid #1f2325',fontSize:13}}><span><b>{r.reward_type}</b><small style={{display:'block',color:'#71797e',marginTop:4}}>{new Date(r.created_at).toLocaleDateString('ko-KR')} · {r.status}</small></span><b>{Number(r.amount).toLocaleString()} {r.asset}</b></div>):<p style={{color:'#737c81'}}>리워드 내역이 없습니다.</p>}</div></section>
  <section style={{marginTop:34}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2 style={{fontSize:26}}>Referral Missions</h2><Link href="/more/reward-hub" style={{color:'#b9ff31',fontSize:13,fontWeight:900}}>Reward Hub ›</Link></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12}}>{[['첫 추천 완료','추천 회원이 정책상 Qualified 상태 달성'],['첫 입금 추천','입금 조건은 운영 캠페인 기준 적용'],['첫 거래 추천','유효 거래량 조건은 서버 정책 기준'],['Milestone','누적 Qualified 추천 인원 구간 달성']].map(([t,d])=><div key={t} style={{padding:20,border:'1px solid #25292c',borderRadius:12,background:'#111315'}}><small style={{color:'#b9ff31',fontWeight:900}}>MISSION</small><h3 style={{margin:'8px 0',fontSize:18}}>{t}</h3><p style={{margin:0,color:'#858d92',fontSize:13,lineHeight:1.6}}>{d}</p></div>)}</div></section>
  <section style={{marginTop:38}}><h2 style={{fontSize:28}}>FAQ</h2><div style={{display:'grid',gap:10}}>{faq.map(([q,a])=><details key={q} style={{border:'1px solid #25292c',borderRadius:9,background:'#0d0f10',padding:'0 20px'}}><summary style={{padding:'18px 0',cursor:'pointer',fontWeight:800}}>{q}</summary><p style={{margin:'0 0 18px',color:'#8f979c',lineHeight:1.7}}>{a}</p></details>)}</div></section>
 </div></main>}
