'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import {createBrowserSupabase} from '@/lib/supabase-browser';

type Course={id:string;slug:string;category:string;title:string;description:string;level:string;estimated_minutes:number};
type Quiz={question?:string;options?:string[];answer?:number};
type Lesson={id:string;slug:string;title:string;content:string;lesson_order:number;quiz?:Quiz|null};
export default function AcademyCoursePage(){
 const p=useParams<{slug:string}>();const supabase=useMemo(()=>createBrowserSupabase(),[]);
 const [course,setCourse]=useState<Course|null>(null),[lessons,setLessons]=useState<Lesson[]>([]),[done,setDone]=useState<Set<string>>(new Set()),[logged,setLogged]=useState(false),[loading,setLoading]=useState(true);
 const [answers,setAnswers]=useState<Record<string,number>>({});
 async function load(){if(!p?.slug)return;const {data:c}=await supabase.from('academy_courses').select('id,slug,category,title,description,level,estimated_minutes').eq('slug',p.slug).eq('published',true).maybeSingle();if(!c){setLoading(false);return;}setCourse(c as Course);const [{data:l},{data:{user}}]=await Promise.all([supabase.from('academy_lessons').select('id,slug,title,content,lesson_order,quiz').eq('course_id',c.id).eq('published',true).order('lesson_order'),supabase.auth.getUser()]);setLessons((l||[]) as Lesson[]);setLogged(!!user);if(user&&l?.length){const ids=l.map(x=>x.id);const {data:pr}=await supabase.from('academy_progress').select('lesson_id').eq('user_id',user.id).in('lesson_id',ids);setDone(new Set((pr||[]).map(x=>x.lesson_id)))}setLoading(false)}
 useEffect(()=>{load()},[p?.slug]);
 async function complete(id:string){const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login';return;}const lesson=lessons.find(x=>x.id===id);const selected=answers[id];const score=lesson?.quiz&&typeof lesson.quiz.answer==='number'?(selected===lesson.quiz.answer?100:0):null;await supabase.from('academy_progress').upsert({user_id:user.id,lesson_id:id,completed_at:new Date().toISOString(),quiz_score:score},{onConflict:'user_id,lesson_id'});setDone(s=>new Set([...s,id]));}
 if(loading)return <main style={{minHeight:'80vh',background:'#08090a',color:'#80898e',display:'grid',placeItems:'center'}}>불러오는 중...</main>;
 if(!course)return <main style={{minHeight:'80vh',background:'#08090a',color:'#fff',display:'grid',placeItems:'center'}}>코스를 찾을 수 없습니다.</main>;
 return <main style={{minHeight:'calc(100vh - 72px)',background:'#08090a',color:'#f4f6f7',padding:'42px 0 90px'}}><div className="xtShell" style={{maxWidth:1000}}><Link href="/more/academy" style={{color:'#8a9297',fontSize:13}}>← Academy</Link><section style={{padding:'28px 0 24px',borderBottom:'1px solid #25292c'}}><small style={{color:'#b9ff31',fontWeight:900}}>{course.category} · {course.level}</small><h1 style={{fontSize:'clamp(34px,5vw,56px)',margin:'10px 0',letterSpacing:'-.04em'}}>{course.title}</h1><p style={{color:'#8e969b',lineHeight:1.7,maxWidth:760}}>{course.description}</p><span style={{fontSize:12,color:'#6f787d'}}>예상 {course.estimated_minutes}분 · 완료 {done.size}/{lessons.length}</span></section><div style={{display:'grid',gap:14,marginTop:24}}>{lessons.length?lessons.map((l,i)=>{const q=l.quiz;const selected=answers[l.id];const answered=selected!==undefined;const correct=answered&&q&&selected===q.answer;return <article key={l.id} style={{border:'1px solid #25292c',borderRadius:14,background:'#0f1112',padding:'22px'}}><div style={{display:'flex',justifyContent:'space-between',gap:15,alignItems:'center'}}><div><small style={{color:'#6f787d'}}>LESSON {String(i+1).padStart(2,'0')}</small><h2 style={{fontSize:22,margin:'6px 0 0'}}>{l.title}</h2></div><button onClick={()=>complete(l.id)} disabled={done.has(l.id)} style={{height:38,padding:'0 14px',borderRadius:8,border:'1px solid '+(done.has(l.id)?'#355718':'#394045'),background:done.has(l.id)?'#17220f':'#171a1c',color:done.has(l.id)?'#b9ff31':'#fff',fontWeight:800,cursor:'pointer'}}>{done.has(l.id)?'완료됨':logged?'학습 완료':'로그인 후 완료'}</button></div><p style={{whiteSpace:'pre-wrap',lineHeight:1.85,color:'#c8cdcf',fontSize:14,margin:'18px 0 0'}}>{l.content}</p>{q?.question&&q.options?.length?<div style={{marginTop:20,padding:18,border:'1px solid #272c2f',background:'#121516',borderRadius:12}}><small style={{color:'#b9ff31',fontWeight:900}}>CHECK QUIZ</small><h3 style={{fontSize:16,margin:'8px 0 12px'}}>{q.question}</h3><div style={{display:'grid',gap:8}}>{q.options.map((opt,idx)=><button key={opt} onClick={()=>setAnswers(a=>({...a,[l.id]:idx}))} style={{textAlign:'left',padding:'11px 12px',borderRadius:8,border:'1px solid '+(selected===idx?'#87c61b':'#2a3033'),background:selected===idx?'#18210f':'#171a1c',color:'#eef1f2',cursor:'pointer'}}>{idx+1}. {opt}</button>)}</div>{answered&&<div style={{marginTop:10,fontSize:12,color:correct?'#b9ff31':'#ff7b88'}}>{correct?'정답입니다.':'다시 생각해보세요.'}</div>}</div>:null}</article>}):<div style={{padding:28,border:'1px solid #25292c',borderRadius:14,color:'#7d858a'}}>이 코스의 강의 콘텐츠를 준비 중입니다.</div>}</div></div></main>}
