'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';

type Partner={partner_code:string;status:string;tier:string;joined_at:string};
type Ref={id:string;status:string;joined_at:string;qualified_at:string|null};
type Reward={id:string;reward_type:string;amount:number;asset:string;status:string;created_at:string;paid_at:string|null};
export default function RewardHubPage(){const supabase=useMemo(()=>createBrowserSupabase(),[]);const [loading,setLoading]=useState(true);const [partner,setPartner]=useState<Partner|null>(null);const [loggedIn,setLoggedIn]=useState(false);const [refs,setRefs]=useState<Ref[]>([]);const [rewards,setRewards]=useState<Reward[]>([]);
 useEffect(()=>{let cancelled=false;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(cancelled)return;if(!user){setLoggedIn(false);setLoading(false);return;}setLoggedIn(true);const [{data:p},{data:r},{data:w}]=await Promise.all([supabase.from('referral_partners').select('partner_code,status,tier,joined_at').eq('user_id',user.id).eq('status','ACTIVE').maybeSingle(),supabase.from('referrals').select('id,status,joined_at,qualified_at').eq('referrer_user_id',user.id).order('joined_at',{ascending:false}),supabase.from('referral_reward_events').select('id,reward_type,amount,asset,status,created_at,paid_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100)]);if(cancelled)return;setPartner((p as Partner|null)||null);setRefs((r||[]) as Ref[]);setRewards((w||[]) as Reward[]);setLoading(false)})();return()=>{cancelled=true}},[supabase]);
 if(loading)return <main style={{minHeight:'calc(100vh - 72px)',background:'#070809',display:'grid',placeItems:'center',color:'#7f888d'}}>Checking partner access…</main>;
 if(!partner)return <main style={{minHeight:'calc(100vh - 72px)',background:'#070809',color:'#f4f6f7',display:'grid',placeItems:'center',padding:24}}><section style={{width:'min(700px,100%)',border:'1px solid #2a2e31',background:'#111315',borderRadius:18,padding:'42px 34px',textAlign:'center'}}><div style={{width:56,height:56,borderRadius:16,display:'grid',placeItems:'center',margin:'0 auto 18px',background:'#1b2117',color:'#b9ff31',fontSize:25}}>◆</div><span style={{fontSize:11,fontWeight:900,letterSpacing:'.14em',color:'#777f84'}}>PARTNER ACCESS ONLY</span><h1 style={{fontSize:'clamp(28px,5vw,42px)',margin:'12px 0 14px'}}>Reward Hub</h1><p style={{fontSize:17,lineHeight:1.7,color:'#b3babd'}}>파트너 전용 실적·커미션·네트워크 관리 화면입니다.</p><div style={{display:'flex',gap:10,justifyContent:'center',flexWrap:'wrap',marginTop:28}}>{!loggedIn&&<Link href="/login" style={{minHeight:44,padding:'0 20px',borderRadius:8,display:'inline-flex',alignItems:'center',background:'#b9ff31',color:'#0d1207',fontWeight:900}}>Log in</Link>}<Link href="/more/referral" style={{minHeight:44,padding:'0 20px',borderRadius:8,display:'inline-flex',alignItems:'center',border:'1px solid #34393d',color:'#e7eaeb',fontWeight:800}}>Referral Program</Link></div></section></main>;
 const qualified=refs.filter(x=>x.status==='QUALIFIED').length;const approved=rewards.filter(x=>x.status==='APPROVED').reduce((s,x)=>s+Number(x.amount||0),0);const paid=rewards.filter(x=>x.status==='PAID').reduce((s,x)=>s+Number(x.amount||0),0);const pending=rewards.filter(x=>x.status==='PENDING').reduce((s,x)=>s+Number(x.amount||0),0);const monthStart=new Date();monthStart.setDate(1);monthStart.setHours(0,0,0,0);const monthQualified=refs.filter(x=>x.qualified_at&&new Date(x.qualified_at)>=monthStart).length;
 return <main style={{minHeight:'calc(100vh - 72px)',background:'#08090a',color:'#f4f6f7',padding:'42px 0 90px'}}><div className="xtShell"><div style={{display:'flex',justifyContent:'space-between',gap:22,alignItems:'flex-end',flexWrap:'wrap',paddingBottom:24,borderBottom:'1px solid #212427'}}><div><span style={{fontSize:11,color:'#777f84',fontWeight:900,letterSpacing:'.14em'}}>REFERRAL PARTNER</span><h1 style={{fontSize:'clamp(38px,5vw,62px)',letterSpacing:'-.045em',margin:'8px 0 8px'}}>Reward Hub</h1><p style={{margin:0,color:'#899196'}}>실제 추천 실적과 커미션 상태를 계정 기준으로 확인합니다.</p></div><div style={{padding:'12px 16px',borderRadius:10,background:'#121517',border:'1px solid #2a2e31',minWidth:230}}><small style={{display:'block',color:'#747c81',marginBottom:5}}>Partner Code</small><b style={{fontSize:18,color:'#b9ff31'}}>{partner.partner_code}</b><small style={{display:'block',color:'#747c81',marginTop:7}}>{partner.tier} · {partner.status}</small></div></div>
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,marginTop:20}}>{[['직접 추천',refs.length],['Qualified',qualified],['이번달 Qualified',monthQualified],['확정 커미션',`${approved.toLocaleString()} USDT`],['지급 완료',`${paid.toLocaleString()} USDT`],['지급 대기',`${pending.toLocaleString()} USDT`]].map(([k,v])=><div key={k} style={{border:'1px solid #25292c',background:'#111315',borderRadius:12,padding:'17px 16px'}}><small style={{display:'block',color:'#747c81',marginBottom:7}}>{k}</small><b style={{fontSize:23}}>{String(v)}</b></div>)}</section>
 <section style={{display:'grid',gridTemplateColumns:'1.05fr .95fr',gap:16,marginTop:18}}><div style={{border:'1px solid #25292c',background:'#0e1011',borderRadius:14,padding:22}}><h2 style={{fontSize:22,margin:'0 0 14px'}}>Referral Performance</h2>{refs.length?refs.slice(0,12).map(r=><div key={r.id} style={{display:'grid',gridTemplateColumns:'1fr 120px 110px',gap:10,padding:'12px 0',borderBottom:'1px solid #1f2325',fontSize:13}}><span>{new Date(r.joined_at).toLocaleDateString('ko-KR')}</span><span>{r.qualified_at?new Date(r.qualified_at).toLocaleDateString('ko-KR'):'—'}</span><b style={{textAlign:'right',color:r.status==='QUALIFIED'?'#b9ff31':'#c3c7c9'}}>{r.status}</b></div>):<p style={{color:'#727b80'}}>아직 추천 실적이 없습니다.</p>}</div><div style={{border:'1px solid #25292c',background:'#0e1011',borderRadius:14,padding:22}}><h2 style={{fontSize:22,margin:'0 0 14px'}}>Commission History</h2>{rewards.length?rewards.slice(0,12).map(r=><div key={r.id} style={{display:'grid',gridTemplateColumns:'1fr auto',gap:10,padding:'12px 0',borderBottom:'1px solid #1f2325',fontSize:13}}><span><b>{r.reward_type}</b><small style={{display:'block',color:'#727b80',marginTop:4}}>{new Date(r.created_at).toLocaleDateString('ko-KR')} · {r.status}</small></span><b>{Number(r.amount).toLocaleString()} {r.asset}</b></div>):<p style={{color:'#727b80'}}>커미션 기록이 없습니다.</p>}</div></section>
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:14,marginTop:18}}>{[['Partner Tier',`${partner.tier} · ${partner.status}`],['Joined',new Date(partner.joined_at).toLocaleDateString('ko-KR')],['Network','현재 직접 추천 실적 기준'],['Reports','확정 기록만 표시']].map(([t,d])=><div key={t} style={{minHeight:120,border:'1px solid #25292c',background:'#111315',borderRadius:14,padding:22}}><span style={{display:'block',color:'#b9ff31',fontSize:11,fontWeight:900,letterSpacing:'.12em',marginBottom:12}}>PARTNER</span><b style={{fontSize:18}}>{t}</b><p style={{color:'#7f888d',fontSize:13,lineHeight:1.65,margin:'10px 0 0'}}>{d}</p></div>)}</section>
 <section style={{marginTop:18,border:'1px solid #25292c',borderRadius:14,background:'#0e1011',padding:24}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><b style={{fontSize:18}}>Partner access verified</b><p style={{color:'#7f888d',fontSize:13,lineHeight:1.65,margin:'7px 0 0'}}>커미션 금액은 referral_reward_events의 서버 확정 기록만 합산합니다.</p></div><Link href="/more/referral" style={{color:'#b9ff31',fontWeight:800,fontSize:13}}>Referral Program ›</Link></div></section></div></main>}
