'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '@/lib/supabase-browser';

type Partner={partner_code:string;status:string;tier:string;joined_at:string};

export default function RewardHubPage(){
 const supabase=useMemo(()=>createBrowserSupabase(),[]);
 const [loading,setLoading]=useState(true);
 const [partner,setPartner]=useState<Partner|null>(null);
 const [loggedIn,setLoggedIn]=useState(false);
 useEffect(()=>{let cancelled=false;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(cancelled)return;if(!user){setLoggedIn(false);setLoading(false);return;}setLoggedIn(true);const {data}=await supabase.from('referral_partners').select('partner_code,status,tier,joined_at').eq('user_id',user.id).eq('status','ACTIVE').maybeSingle();if(cancelled)return;setPartner((data as Partner|null)||null);setLoading(false)})();return()=>{cancelled=true}},[supabase]);
 if(loading)return <main style={{minHeight:'calc(100vh - 72px)',background:'#070809',display:'grid',placeItems:'center',color:'#7f888d'}}>Checking partner access…</main>;
 if(!partner)return <main style={{minHeight:'calc(100vh - 72px)',background:'#070809',color:'#f4f6f7',display:'grid',placeItems:'center',padding:24}}><section style={{width:'min(700px,100%)',border:'1px solid #2a2e31',background:'#111315',borderRadius:18,padding:'42px 34px',textAlign:'center',boxShadow:'0 28px 80px rgba(0,0,0,.38)'}}><div style={{width:56,height:56,borderRadius:16,display:'grid',placeItems:'center',margin:'0 auto 18px',background:'#1b2117',color:'#b9ff31',fontSize:25}}>◆</div><span style={{display:'inline-block',fontSize:11,fontWeight:900,letterSpacing:'.14em',color:'#777f84'}}>PARTNER ACCESS ONLY</span><h1 style={{fontSize:'clamp(28px,5vw,42px)',margin:'12px 0 14px',letterSpacing:'-.04em'}}>Reward Hub</h1><p style={{fontSize:17,lineHeight:1.7,color:'#b3babd',margin:'0 auto',maxWidth:520}}>파트너 전용 실적·커미션·네트워크 관리 화면입니다.</p><p style={{fontSize:13,lineHeight:1.7,color:'#737c81',margin:'10px auto 0',maxWidth:560}}>파트너 승인이 완료된 계정은 자동으로 접근 권한이 활성화됩니다. 일반 회원용 미션/쿠폰형 리워드는 별도 프로그램으로 확장할 수 있습니다.</p><div style={{display:'flex',gap:10,justifyContent:'center',flexWrap:'wrap',marginTop:28}}>{!loggedIn&&<Link href="/login" style={{minHeight:44,padding:'0 20px',borderRadius:8,display:'inline-flex',alignItems:'center',background:'#b9ff31',color:'#0d1207',fontWeight:900}}>Log in</Link>}<Link href="/more/referral" style={{minHeight:44,padding:'0 20px',borderRadius:8,display:'inline-flex',alignItems:'center',border:'1px solid #34393d',color:'#e7eaeb',fontWeight:800}}>Referral Program</Link></div></section></main>;
 return <main style={{minHeight:'calc(100vh - 72px)',background:'#08090a',color:'#f4f6f7',padding:'42px 0 90px'}}><div className="xtShell">
  <div style={{display:'flex',justifyContent:'space-between',gap:22,alignItems:'flex-end',flexWrap:'wrap',paddingBottom:24,borderBottom:'1px solid #212427'}}><div><span style={{fontSize:11,color:'#777f84',fontWeight:900,letterSpacing:'.14em'}}>REFERRAL PARTNER</span><h1 style={{fontSize:'clamp(38px,5vw,62px)',letterSpacing:'-.045em',margin:'8px 0 8px'}}>Reward Hub</h1><p style={{margin:0,color:'#899196'}}>파트너 성과, 커미션, 하위 네트워크, 정산 상태를 한 화면에서 관리합니다.</p></div><div style={{padding:'12px 16px',borderRadius:10,background:'#121517',border:'1px solid #2a2e31',minWidth:230}}><small style={{display:'block',color:'#747c81',marginBottom:5}}>Partner Code</small><b style={{fontSize:18,color:'#b9ff31'}}>{partner.partner_code}</b><small style={{display:'block',color:'#747c81',marginTop:7}}>{partner.tier} · {partner.status}</small></div></div>
  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12,marginTop:20}}>{[['직접 추천','—'],['활성 추천','—'],['하위 파트너','—'],['확정 커미션','—'],['지급 대기','—'],['이번달 실적','—']].map(([k,v])=><div key={k} style={{border:'1px solid #25292c',background:'#111315',borderRadius:12,padding:'17px 16px'}}><small style={{display:'block',color:'#747c81',marginBottom:7}}>{k}</small><b style={{fontSize:23}}>{v}</b></div>)}</section>
  <section style={{display:'grid',gridTemplateColumns:'1.1fr .9fr',gap:16,marginTop:18}}><div style={{border:'1px solid #25292c',background:'#0e1011',borderRadius:14,padding:22}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2 style={{fontSize:22,margin:0}}>Performance Overview</h2><span style={{fontSize:11,color:'#6f787d'}}>30D</span></div><div style={{height:210,display:'grid',placeItems:'center',marginTop:16,border:'1px dashed #2a2e31',borderRadius:10,color:'#697277',fontSize:13}}>실제 파트너 실적 데이터가 연결되면 기간별 차트가 표시됩니다.</div></div><div style={{border:'1px solid #25292c',background:'#0e1011',borderRadius:14,padding:22}}><h2 style={{fontSize:22,margin:'0 0 16px'}}>Partner Tier</h2>{[['Current tier',partner.tier],['Status',partner.status],['Joined',new Date(partner.joined_at).toLocaleDateString('ko-KR')],['Next review','운영 정책 기준']].map(([k,v])=><div key={k} style={{display:'flex',justifyContent:'space-between',gap:14,padding:'13px 0',borderBottom:'1px solid #1f2325',fontSize:13}}><span style={{color:'#798187'}}>{k}</span><b>{v}</b></div>)}</div></section>
  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:14,marginTop:18}}>{[['Referral Performance','가입→인증→입금→거래 단계별 추천 회원 상태를 확인합니다.'],['Commission Summary','예정·확정·지급완료 커미션을 구분해서 확인합니다.'],['Partner Network','직접 추천과 하위 파트너 구조, 티어, 활성상태를 확인합니다.'],['Reports','일/주/월 단위 실적과 지급 내역을 정산 리포트 형태로 확인합니다.']].map(([t,d])=><div key={t} style={{minHeight:155,border:'1px solid #25292c',background:'#111315',borderRadius:14,padding:22}}><span style={{display:'block',color:'#b9ff31',fontSize:11,fontWeight:900,letterSpacing:'.12em',marginBottom:12}}>PARTNER</span><b style={{fontSize:18}}>{t}</b><p style={{color:'#7f888d',fontSize:13,lineHeight:1.65,margin:'10px 0 0'}}>{d}</p></div>)}</section>
  <section style={{display:'grid',gridTemplateColumns:'1.15fr .85fr',gap:16,marginTop:18}}><div style={{border:'1px solid #25292c',background:'#0e1011',borderRadius:14,padding:22}}><h2 style={{fontSize:22,margin:'0 0 14px'}}>Commission History</h2><div style={{display:'grid',gridTemplateColumns:'1fr .8fr .8fr .8fr',fontSize:11,color:'#6f787d',paddingBottom:10}}><span>기간</span><span>기준 실적</span><span>커미션</span><span style={{textAlign:'right'}}>상태</span></div><div style={{padding:'34px 0',borderTop:'1px solid #1f2325',textAlign:'center',color:'#697176'}}>확정된 커미션 기록만 표시됩니다.</div></div><div style={{border:'1px solid #25292c',background:'#0e1011',borderRadius:14,padding:22}}><h2 style={{fontSize:22,margin:'0 0 14px'}}>Network Status</h2>{[['Direct referrals','직접 추천 회원'],['Sub partners','승인된 하위 파트너'],['Active members','정책상 활성 회원'],['Review queue','검토 대기 계정']].map(([a,b])=><div key={a} style={{padding:'12px 0',borderBottom:'1px solid #1f2325'}}><b style={{fontSize:13}}>{a}</b><small style={{display:'block',color:'#788086',marginTop:5}}>{b}</small></div>)}</div></section>
  <section style={{marginTop:18,border:'1px solid #25292c',borderRadius:14,background:'#0e1011',padding:24}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><b style={{fontSize:18}}>Partner access verified</b><p style={{color:'#7f888d',fontSize:13,lineHeight:1.65,margin:'7px 0 0'}}>실제 성과·커미션·지급 데이터는 서버에서 확정된 운영 기록만 사용합니다.</p></div><Link href="/more/referral" style={{color:'#b9ff31',fontWeight:800,fontSize:13}}>Referral Program ›</Link></div></section>
 </div></main>
}
